### ISSUE TITLE
The Blackstone's Arm is buggy

### ISSUE THREAD

**Issue by CamperSamu** [Globox1997/AdventureZ#10]
The Blackstone's Arm charges when not equipped (like when i'm eating), sometimes looses enchantments and metadata and with how it works I can't apply Age of Exile stats to it because they get constantly reloaded.

It should work like a bow, so it doesn't loose its data when charging.

**Comment by CamperSamu** [comment]
I'm working on a fix, I'll commit later this day when everything works.

**Comment by CamperSamu** [comment]
CamperSamu:master

**Comment by CamperSamu** [comment]
fixed in #11.

**Comment by Globox1997** [comment]
Thanks for the pr :)
