### ISSUE TITLE
Piglin Flag texture glitch with shaders

### ISSUE THREAD

**Issue by TJ-Pinkerton** [Globox1997/AdventureZ#100]
So I'm not sure why but the piglin flag turns transparent when shaders are active pls fix
High Shaders
![highendshaders](https://user-images.githubusercontent.com/61664131/166132564-fd32c148-3f87-4ec9-a725-c09bf23c0229.png)
Low Shaders
![lowendshaders](https://user-images.githubusercontent.com/61664131/166132567-6abbca2e-e2f9-4932-9a8d-71068a3bb937.png)
No Shaders
![noshaders](https://user-images.githubusercontent.com/61664131/166132568-ac70b4c8-f4f2-4416-8976-13294586af31.png)

**Comment by Globox1997** [comment]
Definitely needs a fix, thanks for reporting it

**Comment by Globox1997** [comment]
Fixed it but a new issue is there [https://github.com/Globox1997/AdventureZ/commit/f428ec1a6f6a6fee2d1e3f843cb0da3b9aed8a60](https://github.com/Globox1997/AdventureZ/commit/f428ec1a6f6a6fee2d1e3f843cb0da3b9aed8a60)
