### ISSUE TITLE
Crashes on Startup 

### ISSUE THREAD

**Issue by SnoringSnorlax** [Globox1997/AdventureZ#101]
Crashes when i start the minecraft launcher on version 1.18.2
been happening for a while now
downloaded all dependencies 
**to reproduce error:**
Download adventurez and voidz and the dependencies required, 
then start the fabric loader with fabric api v0.53.3 1.18.2

[crash-2022-05-28_15.20.51-client.txt](https://github.com/Globox1997/AdventureZ/files/8790910/crash-2022-05-28_15.20.51-client.txt)
![image](https://user-images.githubusercontent.com/79255936/170820451-4f069e62-c6fd-46c4-8981-c2ccb4f2bcdb.png)

**Comment by Globox1997** [comment]
What happens if you start without the mod roughlysearchable

**Comment by SnoringSnorlax** [comment]
> What happens if you start without the mod roughlysearchable

a new mod error pops up, even though all of them are compatible

**Comment by Globox1997** [comment]
Pls post this new crashlog here

**Comment by Globox1997** [comment]
Reopen with the full crash log
