### ISSUE TITLE
crash on startup 1.19

### ISSUE THREAD

**Issue by 3dguru** [Globox1997/AdventureZ#102]
Receive this error when starting 1.19 v1.4.12

https://pastebin.com/MBQTrRLv

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/a94d1c3462e414c16a09d0a0dab16dbeaa4b3e1c](https://github.com/Globox1997/AdventureZ/commit/a94d1c3462e414c16a09d0a0dab16dbeaa4b3e1c)
