### ISSUE TITLE
Server crash when Java 17 compatibility level cannot be set.

### ISSUE THREAD

**Issue by Fenlas** [Globox1997/AdventureZ#106]
Hey there!

I've assembled a server pack and came across an issue with AdventureZ. I was able to recreate the crash with the following mods on a fresh fabric server install:

> Fabric-API-0.56.1
> Cloth-Config-Fabric-62.62
> AdventureZ-1.4.11

Looking at the log, It seems the compatibility level is being set to java 16 instead of 17. Causing the server to crash.

[log file](https://github.com/Globox1997/AdventureZ/files/8948800/latest.log)

[pastebin link](https://pastebin.com/SujJan9V)

**Comment by Globox1997** [comment]
Looks like it is incompatible with fabric api? AdventureZ is built on api 0.47.10+1.18.2

**Comment by Fenlas** [comment]
Hey, back again.

I believe this issue can be closed now. It seems that using different java types (Like OpenJDK vs oracle) can cause some crashes while running on this mod in a server setup. 

In this instance, using ATLauncher's provided Java runtime along with their server setup should be avoided, and instead use a standalone fabric setup. (using oracle's java runtime)
