### ISSUE TITLE
Massive server crash and deadlock on startup - possible incompat with StyledChat?

### ISSUE THREAD

**Issue by Tempest-5ky** [Globox1997/AdventureZ#112]
Also made an issue for this on StyledChat's github.
Server ran fine, added StyledChat and the server immediately crashed on startup and deadlocked, requiring me to kill it completely. Seems like a good dozen or two mods got broken by it too and threw errors.
https://mclo.gs/JOpG2xU

It's probably an issue on SC's end but I figured i'd bring it up here just in case!

**Comment by Globox1997** [comment]
Looks like the method "styledChat_replaceChatMessage" doesn't exist in later versions., not sure how this redirect affects the adventurez method tho

**Comment by Globox1997** [comment]
Reopen if still still persists with the latest version.
