### ISSUE TITLE
Request/Improvement on Blackstone Golem

### ISSUE THREAD

**Issue by sadlyborger** [Globox1997/AdventureZ#113]
It should attack whoever attacks it. I tried summoning warden on it but it doesn't fight back.

**Comment by sadlyborger** [comment]
I have tried killing it with just netherite armor without enchantment and I could kill it easily. As what it is right now. I don't think it is the hardest enemy. Another suggestion is making each punch of golem add fire? If you got punch, it will set you on fire. Once in a while if you hit him, or a certain amount of damage made, it will spawn some small golems that will help him kill you. He will also throw lava if there's a lava near him

**Comment by Globox1997** [comment]
Those are suggestions I really like, thank you sadlyborger :)
Added fire punch, randomly spawning small golems (5% chance on damage) with [https://github.com/Globox1997/AdventureZ/commit/992da587a1bdb00102f319f61eb0995c55bdcf12](https://github.com/Globox1997/AdventureZ/commit/992da587a1bdb00102f319f61eb0995c55bdcf12)
Not a fan of throwing lava to be honest

**Comment by sadlyborger** [comment]
Thank you soo much for listening. It's fine if it doesn't throw lava. It's still awesome. I also have notice that it doesn't attack who is attacking it. It would be nice to change it to attack the nearest entity that's attacking it. I could just lure it and then my friend would just attack it and it would be finished. I would also suggest giving it 3 phase? Last phase is make him hit harder, faster and increase the spawn of spawning small golems? But its just a suggestion. Still love the mod btw. <3 Keep it up.

**Comment by sadlyborger** [comment]
And is it possible to backport it to 1.19? Since most of the download is 1.19. This new updates?

**Comment by Globox1997** [comment]
Appreciate it :)
Out of time reasons I only work on the latest version of my mods
