### ISSUE TITLE
Dragon cant be tamed

### ISSUE THREAD

**Issue by navrelis** [Globox1997/AdventureZ#114]
I cant tame the dragon in the version 1.19 in multiplayer. When it is hatched it doesnt show the name of the owner and it wont let someone ride it.

**Comment by navrelis** [comment]
![image](https://user-images.githubusercontent.com/111079703/184195710-8c16dcb6-b7ef-4388-bbca-3377c707a53e.png)

**Comment by Globox1997** [comment]
You have to feed it orc skin to tame it :)

**Comment by Globox1997** [comment]
I could change it to everybody can ride it when it is tamed, what do you think?
