### ISSUE TITLE
Make end warthogs a bit more balanced please!

### ISSUE THREAD

**Issue by Skeithh** [Globox1997/AdventureZ#118]
While we can adjust the spawn rates fine, fighting an end warthog is nigh-impossible for many of us as their hitbox is just a tad too small and their rapid attacks are way too overpowered for the amount of damage they can do in such a small time, and with the knockback. Please balance them! It's no fun fighting these things, moreso just plain frustrating as they keep knocking you miles away, getting three hits in at once, before you can even get a single hit in. Some sort of tweaking would be highly appreciated, because until then we're massively reducing their spawn rate.

**Comment by FaultyFunctions** [comment]
Fighting them with a bow works the best but since their spawn rate is so incredibly high, it makes traversal of the end super frustrating. I'd rather not have exploring the biomes of a mod like BetterEnd ruined by one mob that spawns constantly in every single biome that is frustrating to melee.

**Comment by Globox1997** [comment]
Balanced it a little with [https://github.com/Globox1997/AdventureZ/commit/135e51f84cf92e2589b98bb1e48f48df8591d45a](https://github.com/Globox1997/AdventureZ/commit/135e51f84cf92e2589b98bb1e48f48df8591d45a)
