### ISSUE TITLE
Fungi are quiet.  Too quiet.

### ISSUE THREAD

**Issue by FewerFlaws** [Globox1997/AdventureZ#12]
1. Fungi do not make any sounds at all.  Not when hurt, dying, etc.
2. Fungi do not spawn at all.  I'm assuming weight 100 should make a few show up in the mushroom fields biome.

That being said, fungi are not on the decription page of the mod, so I suspect they are unfinished and disabled.  Just mentioning this in case I'm mistaken about that.

**Comment by Globox1997** [comment]
Nice title :D I actually don't know why they shouldn't make any sounds...
Tested it again in a fresh world and they spawn naturally in the rare mushroom biome and make cute sounds.
they are not mentioned cause I'm too lazy to update the mod page xD

**Comment by FewerFlaws** [comment]
Holy shit are those things noisy.  My apologies.  I guess I had friendly mob sounds turned off >_<

**Comment by Globox1997** [comment]
maybe they are a little too loud xD
