### ISSUE TITLE
Whale and lead interaction

### ISSUE THREAD

**Issue by ouroborus** [Globox1997/AdventureZ#120]
* You can attach a lead to a whale.
* The whale wanders as though it didn't have a lead attached.
* The lead doesn't break even when the whale wanders a long ways away.

I'm not sure which of these things is considered a bug but, altogether, there's a bug in there.

**Comment by Globox1997** [comment]
Fixed lead bug with [https://github.com/Globox1997/AdventureZ/commit/c0c03c9bd7acd9bf20a83a15e6127e3111e66332](https://github.com/Globox1997/AdventureZ/commit/c0c03c9bd7acd9bf20a83a15e6127e3111e66332)
Now the whale can not be leashed
