### ISSUE TITLE
Blackstone Arm Stopped Working, Possibly because of Immmersive portals?

### ISSUE THREAD

**Issue by FooFooBoss** [Globox1997/AdventureZ#121]
So my friend and I were mucking around with the Blackstone Arm and i shot it into the nether portal. The Blackstone arm still shoots but it doesn't blow up or do any damage, neither does it give effects. This happens whenever it is shot, even at the ground or a player.

Edit 1: Ok so just to update this it does give effects when it hits entities but it no longer explodes

**Comment by FooFooBoss** [comment]
Ok so just to update this it does give effects when it hits entities but it no longer explodes

**Comment by Globox1997** [comment]
The secret effect of the blackstone golem arm only works while having the blackstone effect
