### ISSUE TITLE
The Eye never flies down

### ISSUE THREAD

**Issue by KieranStokes** [Globox1997/AdventureZ#122]
https://github.com/Globox1997/AdventureZ/blob/ad975fd071c5349a862b07bc80ba6bdf8ac656ea/src/main/java/net/adventurez/entity/TheEyeEntity.java#L178

This is an unreachable block inside this if statement. The nested if `(this.getY() < entity.getY() + 12.0D)` and `(this.getY() > entity.getY() + 26.0D)` cannot be true at the same time.

This seems to cause the Eye to never travel down, but it will continue to fly upwards if the player is above it.

**Comment by Globox1997** [comment]
Thanks for figuring this out. Fixed with [https://github.com/Globox1997/AdventureZ/commit/6dacd5fbe01ae2b765c97e7406c35b18399ccb31](https://github.com/Globox1997/AdventureZ/commit/6dacd5fbe01ae2b765c97e7406c35b18399ccb31)
