### ISSUE TITLE
Blaze Guardian Shields dont render when using summon command

### ISSUE THREAD

**Issue by TheonlyTazz** [Globox1997/AdventureZ#123]
Minecraft Version: 1.19.2
Fabric Version: 0.14.9
Mod Version: adventurez-1.4.16.jar

when trying to summon a Blaze Guardian through commands (/summon blaze_guardian ~ ~ ~) it will summon the Blaze Guardian, but it wont render it shields untill you relog or change dimensions and back

![image](https://user-images.githubusercontent.com/3908847/197239117-e77f9b54-14dc-4906-969e-266f2e2da614.png)

**Comment by Globox1997** [comment]
Actually a known bug to me, thanks for opening this issue :)

**Comment by TheonlyTazz** [comment]
any update on this issue? i would like to use this in my upcoming modpack

**Comment by Globox1997** [comment]
Fixed this old bug with far too much time with [https://github.com/Globox1997/AdventureZ/commit/a564df7e291835ce89eb593f0e5d4b81b45af792](https://github.com/Globox1997/AdventureZ/commit/a564df7e291835ce89eb593f0e5d4b81b45af792)
