### ISSUE TITLE
only one void shadow boss per server?

### ISSUE THREAD

**Issue by kimiko69** [Globox1997/AdventureZ#125]
im on a small server and someone had already killed the void shadow to hatch their dragon egg. i went to kill it much later and was able to kill the eye just fine but when i went through the portal there was no boss. there was 2 void crystals that i thought killing might trigger the boss but still nothing happened. is this a bug or intentional?

**Comment by Globox1997** [comment]
Don't remember the default settings nut check the voidz settings

**Comment by purejosh** [comment]
You have to change the setting in the voidz config. 

Close this ticket once you've done so, @kimiko69.
