### ISSUE TITLE
Mammoth, mushroom, rhino and reaper spawn

### ISSUE THREAD

**Issue by Mahadbaloch** [Globox1997/AdventureZ#130]
None of these mobs spawn in my world. Even after doubling spawn rates I have not seen a single one of these. Are they extremely rare? Because every other mob spawns fine, even iguana though its a little rare. In the nether I see nightmare spawn many times but never reaper.

I checked all these in their specific biomes.

**Comment by Globox1997** [comment]
No they are not that rare except for the rhino. Reopen if that is still the case in vanilla biomes on the latest version.

**Comment by Mahadbaloch** [comment]
yeah they work now this was very old
