### ISSUE TITLE
No clear way to open Dragon UI to put chest/take of saddle and cannot feed.

### ISSUE THREAD

**Issue by SatyricL** [Globox1997/AdventureZ#131]
Not sure if there is a conflict with other mods in the Better Minecraft pack, but I am currently unable to feed my dragon. Right clicking with the orc skins/raw meat just mounts the dragon instead. 

Trying to add a chest to the dragon doesnt work either. (EDIT: Nvm it just doesnt work with colored chests)

Also, just a suggestion, but the option to disable dismount from the dragon would be awesome. Or have the dragon automaically descend. Having to build a tower up to my dragon every time I accidentally dismount is rough.

**Comment by Ramintta** [comment]
Also can not heal my dragon, and it does not heal itself overtime. What should be the problem?

**Comment by Riyuukii** [comment]
I play better minecraft too, we need to sneak + right click with raw meat to heal our dragon. But I can't find any way to take out my saddle or chest from my dragon.

**Comment by Globox1997** [comment]
Same issue as [https://github.com/Globox1997/AdventureZ/issues/129](https://github.com/Globox1997/AdventureZ/issues/129)
