### ISSUE TITLE
Soul reapers get off the horse (Nightmares)

### ISSUE THREAD

**Issue by billpapat** [Globox1997/AdventureZ#133]
When the **nightmare (horse) goes up on to 2 legs**, the **Reaper Gets off the nightmare**

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/f82b01000d359075f18f6697b16bb1c2ae2b1767](https://github.com/Globox1997/AdventureZ/commit/f82b01000d359075f18f6697b16bb1c2ae2b1767)
