### ISSUE TITLE
VoidZ Void Shadow not respawning in server: Negative tick countdown

### ISSUE THREAD

**Issue by dbravo4** [Globox1997/AdventureZ#135]
As shown below, the timer says `The Void Shadow will respawn in -68193724 ticks` which is definitely impossible to countdown to 0 from. 
![image](https://user-images.githubusercontent.com/118207181/227821194-aae419fc-7028-43e6-aaa8-09c8044c3162.png)

Here is how the config for VoidZ is set:
![image](https://user-images.githubusercontent.com/118207181/227821509-d6b50e13-10d9-4cf7-a5df-5abae94bae43.png)

When checking the timer again, it keeps going down in the negatives:
![image](https://user-images.githubusercontent.com/118207181/227821753-fd1d077e-db20-4e01-a7df-68e3da4d1ba6.png)

**Comment by Globox1997** [comment]
This sounds like a bug to me, did you test it on another world?
Please try that and reopen if still happening with the latest version.
