### ISSUE TITLE
At least 5 entity types added by this mod suffocate when in Ad Astra planets when they shouldn't.

### ISSUE THREAD

**Issue by James103** [Globox1997/AdventureZ#136]
There are at least 5 entity types added by this mod which require oxygen to breathe in Ad Astra planets even though they shouldn't.

These entities are golems and the vanilla Iron Golem survives fine without oxygen in Ad Astra planets.
* `adventurez:amethyst_golem`
* `adventurez:small_stone_golem`
* `adventurez:stone_golem`

This entity is based on a skeleton and vanilla skeletons (and undead creatures in general) survive without oxygen:
* `adventurez:summoner`

This entity is based on a wither skeleton, which is an undead mob that survives without oxygen:
* `adventurez:wither_puppet`

Adding the mentioned entity types to the tag `#ad_astra:entities/lives_without_oxygen` should resolve this issue.

Originally found in modpack "All of Fabric 6" version 1.5.0.
Minecraft 1.19.2
Fabric Loader 0.14.7
Fabric API 0.75.1
AdventureZ 1.4.17

**Comment by Globox1997** [comment]
Added to the latest version with [https://github.com/Globox1997/AdventureZ/commit/845e821b8022aa3387059b939dbbf41e33655115](https://github.com/Globox1997/AdventureZ/commit/845e821b8022aa3387059b939dbbf41e33655115)
You can add these by yourself by creating a simple datapack.
