### ISSUE TITLE
Suggestion: Projectiles can damage blaze guardians from above and below

### ISSUE THREAD

**Issue by CTH999** [Globox1997/AdventureZ#137]
So, Blaze Guardians have shields on them. But, their heads and legs (on the vertical axis) aren't protected.
So, I propose that arrows can damage them if fired from above (or at a slight angle from above) or bellow. Because of that, they will try to match the height of the player, or move diagonaly enough that you can't hit their head. But, if you get them semi-trapped... now a bow can work!

Just a thought, but one that, at least I think, is pretty brilliant!

Ultimately though, it's your mod and your decision!

**Comment by Globox1997** [comment]
Blaze Guardians can get damaged if you don't hit the shields, you just have to be accurate :)
