### ISSUE TITLE
Crash on startup 1.19.3 - 1.4.17

### ISSUE THREAD

**Issue by Lart-Iste** [Globox1997/AdventureZ#138]
Hi, my game crash on startup with this code of exit 1 (0x1)

To Reproduce :
I don't know how to reproduce this, I think its specific with my mod list and one or more conflicts, but where and why .... ^^

Expected behavior :
Launch the game properly

Screenshots & Logs :
https://paste.ee/p/usops

Mod Version :
1.4.17 Fabric

Additional context :
Ask me ^^

**Comment by Globox1997** [comment]
This mod isn't updated to 1.19.3+
I probably skip versions until 1.20

**Comment by Lart-Iste** [comment]
So it must be an error if on modrinth when I filter by version I find a 1.19.3?

**Comment by Globox1997** [comment]
Yes probably.
