### ISSUE TITLE
[Enhancement] Guilded Netherite Set Bonus Config

### ISSUE THREAD

**Issue by milkev** [Globox1997/AdventureZ#14]
It would be awesome if the set bonus for guilded netherite had a config option, either for disabling it, or changing the duration/effects it gives.
The set effect is cool, and I wouldnt mind it in a vanilla + adventurez environment. However it does not fit with other modded armour sets, being the only one with a set/special effect.

**Comment by Globox1997** [comment]
I think that makes this armor special^^ In my opinion most of the armor other mods are adding to the game are too powerful so the gilded netherite armor has the same stats but with the piglin calming + set bonus

**Comment by Globox1997** [comment]
Added a config option :) [https://github.com/Globox1997/AdventureZ/commit/a2da23c8e3279f1f228791bec4023198c75c9ba7](https://github.com/Globox1997/AdventureZ/commit/a2da23c8e3279f1f228791bec4023198c75c9ba7)
