### ISSUE TITLE
Crash while generating world

### ISSUE THREAD

**Issue by Skidamek** [Globox1997/AdventureZ#140]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.19

### Mod Version

1.4.17

### Describe the Issue

I didn't test if this is some incompatibility with my other mods but it crashes
1. Install adventurez and chunky
2. Start pregenerating world with big radious
3. Wait for crash

### latest.log

[latest.log](https://github.com/Globox1997/AdventureZ/files/11404424/latest.log)

### Do you use any other mods except the required ones?

Yes i do, they are in the logs

**Comment by Skidamek** [comment]
[latest.log](https://github.com/Globox1997/AdventureZ/files/11404475/latest.log)
After restarting, continuing pre-gen, it crashed again

**Comment by Globox1997** [comment]
This should not happen:
Caused by: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "type" is null 	at net.minecraft.class_1917.handler$zij000$adventurez$setEntityId(class_1917.java:1536) ~[server-intermediary.jar:?]

**Comment by Skidamek** [comment]
But it does....

**Comment by Skidamek** [comment]
I pre-generated that world to 100% (radius 5000) with my patch and that crash didn't happen anymore :)

**Comment by Globox1997** [comment]
Uploaded the fix
