### ISSUE TITLE
Enderwarthogs wont spawn on player placed blocks

### ISSUE THREAD

**Issue by Sintix** [Globox1997/AdventureZ#144]
### Minecraft Version

1.19.x

### Mod Loader Version

fabric-api-0.76.0+1.19.2

### Mod Version

adventurez-1.4.18+1.19.2

### Describe the Issue

In the umbra valley biome from better end, i have everything spawn proofed and a farm made, but no warthogs are spawning. the spawning platform is 25x25 so that shouldnt be an issue. when i make a spot un spawn proofed, the warthogs spawn there like crazy. im just wondering if thats meant to be that way or not.

Same thing happens in the small end islands biome from vanilla

### latest.log

N/A

### Do you use any other mods except the required ones?

Better End

**Comment by Globox1997** [comment]
Enderwarthogs are not meant to being farmed ;)
