### ISSUE TITLE
cannot load in 1.20.1

### ISSUE THREAD

**Issue by ShiftySpace** [Globox1997/AdventureZ#146]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.18

### Describe the Issue

Been trying to update my server to 1.20.1 however adventureZ is the only 1.20 mod that doesn't allow 1.20.1. Is there a specific reason why it cannot load on 1.20.1?

### latest.log

[latest.log](https://github.com/Globox1997/AdventureZ/files/12034837/latest.log)

### Do you use any other mods except the required ones?

I disabled all other non required mods to test this just in case.

**Comment by conetopia** [comment]
@ShiftySpace  if you have windows 7,8,10,11 ect. you can get the 7.zip program.
you can open the Adventurez.jar ( without extracting ) then open the fabric.mod.json
computer will ask with what program, you can use Notepad , Notepad++ or any other editor for text.
* Dependency * Minecraft 1.20 , you can change to 1.20.1
Once you save/close the text editor, and then close the 7.zip window, it will ask if you would like to update the archive , click yes.

Boom Saved.

Enjoy Adventurez on 1.20.1 :)


But yeah I would like to see a 1.20.1 Official Update as well.

**Comment by ShiftySpace** [comment]
Thank you so much @conetopia I knew you could change it by editing a file but I didn't know the right way of doing it. This helps me so much!

**Comment by rainysux** [comment]
I tried changing it and it did not work for me. It starts but none of the content loads
> @ShiftySpace if you have windows 7,8,10,11 ect. you can get the 7.zip program. you can open the Adventurez.jar ( without extracting ) then open the fabric.mod.json computer will ask with what program, you can use Notepad , Notepad++ or any other editor for text.
> 
> * Dependency * Minecraft 1.20 , you can change to 1.20.1
>   Once you save/close the text editor, and then close the 7.zip window, it will ask if you would like to update the archive , click yes.
> 
> Boom Saved.
> 
> Enjoy Adventurez on 1.20.1 :)
> 
> But yeah I would like to see a 1.20.1 Official Update as well.

**Comment by Globox1997** [comment]
This should be fixed with the latest release so you won't need dependency override anymore.
