### ISSUE TITLE
Crashed boss The Eye

### ISSUE THREAD

**Issue by Nachouu** [Globox1997/AdventureZ#147]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.18

### Describe the Issue

The world crashes when I kill the boss The Eye

### latest.log

[latest.log](https://github.com/Globox1997/AdventureZ/files/12063086/latest.log)

### Do you use any other mods except the required ones?

yes

**Comment by Globox1997** [comment]
This is very odd, have to look into this.

**Comment by Nachouu** [comment]
Thank you! I have a friend who codes for minecraft servers and I showed him the same log, he said it's the mod's problem and not ours, I hope it can be solved, we love the variety of mods you have!

**Comment by Mahadbaloch** [comment]
@Globox1997 It seems the 1.20 version always crashes when trying to generate the portal block when the eye is killed. I saw this issue on the voidZ page too

**Comment by Globox1997** [comment]
Do you have the latest version of adventurez and voidz installed?

**Comment by Mahadbaloch** [comment]
I have the latest 1.20 version. Not 1.20.1 though. Was it patched after?

**Comment by Globox1997** [comment]
Please try it and give me feedback :)

**Comment by Mahadbaloch** [comment]
Tested on 1.20.1, only adventurez and voidz installed with dependancies. Eye does not crash the game and spawns void portal, but it is not functional, behaves like a simple air block with different texture. Same in all dimensions.
![2023-08-18_14 43 06](https://github.com/Globox1997/AdventureZ/assets/110735899/184b9750-c9a5-4ff2-93df-380964ba8f9f)

**Comment by Globox1997** [comment]
The portal works with right click ;) I guess this can get closed then.
Reopen if still crashing.
