### ISSUE TITLE
Explosions only harm one entity

### ISSUE THREAD

**Issue by FewerFlaws** [Globox1997/AdventureZ#15]
There is [code](https://github.com/Globox1997/AdventureZ/blob/master/src/main/java/net/adventurez/mixin/ExplosionMixin.java#L37) in here that makes all explosions neglect to harm non-player entities on a regular basis.  This clearly goes beyond the scope of the mod.

I tested this by dropping TNT directly on top of a group of innocent chickens.  The death of the most unlucky one is on your shoulders >=(

![2021-01-24_21 48 40](https://user-images.githubusercontent.com/75643699/105666587-6fdc2f00-5e8e-11eb-9912-028911a37fa0.png)

**Comment by FewerFlaws** [comment]
Oh, it seems to harm more than one.  In three separate tests a block of TNT harmed less than half of a group of 5+ chickens every time.  After uninstalling AdventureZ the tnt killed every chicken as expected.

**Comment by Globox1997** [comment]
Definitely gonna fix it, don't know what got me there xD

**Comment by FewerFlaws** [comment]
Based on the commit history it looked like there used to be code preventing friendly fire from the blaze spawn, but then that got generalized too far =]

**Comment by Globox1997** [comment]
way to far xD the idea behind it, is to prevent damaging all mobs when the blaze guardian does its explosion attack

**Comment by Globox1997** [comment]
how did you find out, that this mod makes trouble with that? :D

**Comment by FewerFlaws** [comment]
I'm working on a mod pack and was poking around in the source code.  At the moment I'm making documentation on the  effect each mod has on each biome.  I believe I was investigating the spawn system for soul reapers when I noticed the explosion mixin and wondered why it was there =]

**Comment by Globox1997** [comment]
Should be fixed with this commit[https://github.com/Globox1997/AdventureZ/commit/416493f006099626afa52e9cda57c4949d4726bc](https://github.com/Globox1997/AdventureZ/commit/416493f006099626afa52e9cda57c4949d4726bc)
