### ISSUE TITLE
Game won't start after adding Over Enchanted

### ISSUE THREAD

**Issue by gustafah** [Globox1997/AdventureZ#151]
### Minecraft Version

1.20.x

### Mod Loader Version

Fabric 0.14.21

### Mod Version

1.4.18

### Describe the Issue

I've been adding a few mods to my modpack and ran on the following issue when I added the mod Over Enchanted:

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method updateResultModifyMixin(I)I in adventurez.mixins.json:AnvilScreenHandlerMixin from mod adventurez failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap adventurez-refmap.json

### latest.log

[2023-07-24-5.log](https://github.com/Globox1997/AdventureZ/files/12163785/2023-07-24-5.log)

### Do you use any other mods except the required ones?

Over Enchanted

**Comment by Globox1997** [comment]
Over enchanted probably modifies the same variable as adventurez which makes it incompatible together. Just checked the repo, here it is: [https://github.com/MastroCaleb/OverEnchanted/blob/main/src/main/java/caleb/overenchanted/mixin/UnlimitedLevelsMixin.java#L45](https://github.com/MastroCaleb/OverEnchanted/blob/main/src/main/java/caleb/overenchanted/mixin/UnlimitedLevelsMixin.java#L45)
I can disable the mixin when this mod is loaded but it will disable the feature that books can get enchanted higher than vanilla levels.

**Comment by Mahadbaloch** [comment]
You could do that and make it show a warning telling that the feature is disabled if that mod is installed. Iris does this when notenoughcrashes is installed

**Comment by Globox1997** [comment]
Added disable info with [https://github.com/Globox1997/AdventureZ/commit/7fdc219dee073faf697a6f081a75c9c2c81e6723](https://github.com/Globox1997/AdventureZ/commit/7fdc219dee073faf697a6f081a75c9c2c81e6723)
