### ISSUE TITLE
Ticking Blockentity

### ISSUE THREAD

**Issue by terrarian10** [Globox1997/AdventureZ#153]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21

### Mod Version

1.4.18

### Describe the Issue

Every mob spawner is now, simply put, a ticking block entity

### latest.log

https://gist.github.com/terrarian10/0983f5d912d55da9a089a9aba75e7b02

### Do you use any other mods except the required ones?

Yes, but even after removing mods (including this), ticking block entities will still occur

**Comment by Globox1997** [comment]
Should be fixed with a later update.
[https://github.com/Globox1997/AdventureZ/commit/4aaaee5f16f6e107b821e9b6e13bf31a2b4b0568](https://github.com/Globox1997/AdventureZ/commit/4aaaee5f16f6e107b821e9b6e13bf31a2b4b0568)
