### ISSUE TITLE
Crash server when try kill Dragon

### ISSUE THREAD

**Issue by mindryder** [Globox1997/AdventureZ#154]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric-api-0.86.1+1.20.1

### Mod Version

adventurez-1.4.18

### Describe the Issue

Crash server when try kill Dragon

### latest.log

[crash-2023-08-15_21.31.52-server.txt](https://github.com/Globox1997/AdventureZ/files/12352083/crash-2023-08-15_21.31.52-server.txt)
[crash-2023-08-15_21.25.57-server.txt](https://github.com/Globox1997/AdventureZ/files/12352084/crash-2023-08-15_21.25.57-server.txt)
[crash-2023-08-15_21.27.00-server.txt](https://github.com/Globox1997/AdventureZ/files/12352085/crash-2023-08-15_21.27.00-server.txt)
[crash-2023-08-15_21.28.25-server.txt](https://github.com/Globox1997/AdventureZ/files/12352086/crash-2023-08-15_21.28.25-server.txt)

**Comment by Globox1997** [comment]
I wonder how this can happen.
However this should fix the issue [https://github.com/Globox1997/AdventureZ/commit/b89f0d2e4503cf05903f62939568ff7b19806ae7](https://github.com/Globox1997/AdventureZ/commit/b89f0d2e4503cf05903f62939568ff7b19806ae7)
Reopen if the latest version still crashes
