### ISSUE TITLE
Cannot refill the "Prime Eye" Item using the smithing table

### ISSUE THREAD

**Issue by EssiPando** [Globox1997/AdventureZ#155]
### Minecraft Version

1.20.x

### Mod Loader Version

1.20

### Mod Version

1.4.18

### Describe the Issue

Cannot place prime eye and ender eye into the slots in the smithing table

### latest.log

.

### Do you use any other mods except the required ones?

no

**Comment by Globox1997** [comment]
True, thanks for reporting, moved to anvil with [https://github.com/Globox1997/AdventureZ/commit/1272e033e084d37eaab0984baed394aa97b323d6](https://github.com/Globox1997/AdventureZ/commit/1272e033e084d37eaab0984baed394aa97b323d6)
