### ISSUE TITLE
Patchouli handbook in survival

### ISSUE THREAD

**Issue by Fireeyeeian** [Globox1997/AdventureZ#156]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

It would be nice if when the player spawns the handbook would be added to the players inventory

**Comment by Globox1997** [comment]
not a bad idea but I have no plans to add the handbook to the inventory cause imo it gets too cluttered.
Use a mod like patchoulibutton :)
