### ISSUE TITLE
How come it's not more configurable

### ISSUE THREAD

**Issue by tedude3** [Globox1997/AdventureZ#159]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

i like this mod and a lot of the mobs included in it, but there are some mobs that in my opinion don't really fit and would love to remove in config, but i can't, and that annoys me, so if possible could you add more config options to disable certain mobs

**Comment by Globox1997** [comment]
You can check out the config.
