### ISSUE TITLE
Void Dimension Portal Issue

### ISSUE THREAD

**Issue by Karljotr** [Globox1997/AdventureZ#166]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.25

### Mod Version

Prominence II 

### Describe the Issue

After killing The Eye Boss, clicking on the portal to the Void Dimension (the portal is invisible) you are ported to an empty block and fall into the void losing everything. Since there is no building or flying, it's impossible to load fast enough to water bucket. Portal seems to be embedded in void bedrock layer. 
![void hole](https://github.com/Globox1997/AdventureZ/assets/156557723/4910c271-2e39-4f1f-8411-4eed6aab64bd)

### latest.log

I don't have a log, there is no crash involved. How do I 

### Do you use any other mods except the required ones?

No.

**Comment by Globox1997** [comment]
Fixed on VoidZs side with the latest update.
