### ISSUE TITLE
outdated structure causing DFU usage on current releases

### ISSUE THREAD

**Issue by Linguardium** [Globox1997/AdventureZ#177]
### Minecraft Version

1.20.x

### Mod Loader Version

N/A

### Mod Version

1.4.20

### Describe the Issue

title. You have not kept the versioning of your NBT up to date which means that every time your structure spawns, it loads up DFU to try to fix it. please update the structure. it may be best to do this as part of the datagen/build cycle automatically.

src/main/resources/data/adventurez/structures/eyeland.nbt

### latest.log

N/A

**Comment by Globox1997** [comment]
Should be updated in 1.21

**Comment by Linguardium** [comment]
Thanks for the hard work. This mod is great and the effort shows.
