### ISSUE TITLE
Soul Reapers and Nightmares don't despawn, but count towards the mob cap, ruining farms

### ISSUE THREAD

**Issue by g5bb** [Globox1997/AdventureZ#18]
I made a wither skeleton farm, and it wasn't working. So I decided to kill all Nightmares and Soul Reapers, and it started working. To fix this, either...
1. Soul reapers/nightmares should not count towards the mobcap.
OR
2. Soul reapers/nightmares should despawn like normal mobs.

This probably applies to the other naturally spawning bosses aswell, so that should be fixed.

**Comment by Globox1997** [comment]
should be an easy fix ;)

**Comment by Globox1997** [comment]
Should be fixed with this commit [https://github.com/Globox1997/AdventureZ/commit/dff8e903eaf8890980b0f74460bb3d562133fa8d](https://github.com/Globox1997/AdventureZ/commit/dff8e903eaf8890980b0f74460bb3d562133fa8d)
