### ISSUE TITLE
The Eye Shrine

### ISSUE THREAD

**Issue by lorddodo02** [Globox1997/AdventureZ#181]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.11

### Mod Version

1.4.20

### Describe the Issue

I cannot summon The Eye. When i try to summon through the shrine, Dragon Egg breaks and The Eye appears for a moment and then disappears

https://github.com/user-attachments/assets/9d4a3c11-48cf-431d-938f-ad462191b3ec

### latest.log

[latest.log](https://github.com/user-attachments/files/16442291/latest.log)

### Do you use any other mods except the required ones?

Better MC [FABRIC] 1.20.1 v25

**Comment by Globox1997** [comment]
Are you in peaceful mode?

**Comment by lorddodo02** [comment]
I was trying to summon it in creative mode and i think i was in peaceful mode :) My stupidity. Sorry for bothering you
