### ISSUE TITLE
`TheEyeEntity` should implements `Monster` for better compatibility

### ISSUE THREAD

**Issue by Karashok-Leo** [Globox1997/AdventureZ#183]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug/feature.

### Description of your suggestion.

`TheEyeEntity` should implements `Monster` for better compatibility

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/AdventureZ/commit/886ba601043d3749befa7a9003682be769951975](https://github.com/Globox1997/AdventureZ/commit/886ba601043d3749befa7a9003682be769951975)
