### ISSUE TITLE
Skulls from Soul Reapers are very common.

### ISSUE THREAD

**Issue by DitDitGitHub** [Globox1997/AdventureZ#19]
I've killed ~5 of them and gotten 2 skulls without looting... looking in the loot tables it says it's a 0.45 chance without looting, so is this a bug or am I just getting very lucky?

**Comment by Globox1997** [comment]
you are very lucky :D 
just kidding, 0.45 is very high (almost every second kill you should drop one).

**Comment by DitDitGitHub** [comment]
Oh I see now. 0.45 out of 1, not 0.45 out of 100, which are good odds in my mind. In my opinion, that is really OP. It removes half the purpose for a nether fortress - to grind for Wither Skulls. I'll probably alter the chances myself but this removes balance in my opinion, especially for servers. Wither Skulls are normally this hard-to-obtain object which sell for quite a lot, but now a quick trip to a soul sand valley and you'll have one within 10 minutes, even without looting.

**Comment by Globox1997** [comment]
Okay, I think I should decrease the chance, any suggestions?

**Comment by DitDitGitHub** [comment]
I personally have it set to 0.008 (0.8%) without looting and rising by 0.004 (0.4%) with each looting level, for a max of 0.02 (2%). This will make nether fortresses preferable as these chances are just a third of a Wither Skeletons but still keeps these mobs as a viable option if you have looting.

**Comment by Globox1997** [comment]
changed the drop rate to 3%, that means a 0.5% higher chance than the normal wither skeleton :)
