### ISSUE TITLE
Mobs spawn in Doors of Infinity dimensions

### ISSUE THREAD

**Issue by srnyx** [Globox1997/AdventureZ#24]
Mobs will spawn naturally in the doors of infinity dimensions.
Doors of Infinity: https://www.curseforge.com/minecraft/mc-mods/doors-of-infinity

![image](https://user-images.githubusercontent.com/25808801/111080907-1af48680-84d7-11eb-8467-9a2bdbed3f23.png)

**Comment by Globox1997** [comment]
This is not AdventureZ related, please open an Issue at the MobZ repo
