### ISSUE TITLE
Orcs always spawn with the same amount of HP regardless of their max HP

### ISSUE THREAD

**Issue by itsNordLord** [Globox1997/AdventureZ#26]
https://imgur.com/a/ZfMxKe0 (Video file was larger than 10MB)
![image](https://user-images.githubusercontent.com/68762570/112066603-e6f71200-8b23-11eb-9442-df7e3aef0f95.png)

Some other things:
- Their drops may need to be adjusted. I can't seem to get any Orc Skin drops even with Looting 3 & spawning them in with eggs
- They have an attack range of like 3 or 4 blocks which doesn't represent their model very well and leads to confusion
- Orcs should have another drop besides Orc Skin which has finite uses. Orcs are usually brutish, maybe have them drop a tooth that makes knockback potions

p.s. your models look fantastic!

**Comment by Globox1997** [comment]
Fixed loot table (had a typo o_o) [b44b875620c591bbc2df2086e2d69baec2afe05f](b44b875620c591bbc2df2086e2d69baec2afe05f)

**Comment by Globox1997** [comment]
Fixed attack range and orc health [https://github.com/Globox1997/AdventureZ/commit/b1589b66f1a0ab436fd920478404b379e59bd9ee](https://github.com/Globox1997/AdventureZ/commit/b1589b66f1a0ab436fd920478404b379e59bd9ee)
No plans to add other items to the loot table currently
