### ISSUE TITLE
New texture for patchouli wiki book

### ISSUE THREAD

**Issue by CCCClear** [Globox1997/AdventureZ#27]
![book](https://user-images.githubusercontent.com/44665051/113031154-ec59f980-91c0-11eb-9324-476b1c9acc4e.png)

![book1](https://user-images.githubusercontent.com/44665051/113032208-2e376f80-91c2-11eb-9cfe-77044eadc6bb.png)

Inspired by orc skins, and because the book has a living eye, it can only be sealed.

**Comment by Globox1997** [comment]
hehe, already created a texture for the book here[https://github.com/Globox1997/AdventureZ/commit/f6c3d71e08e646cc04dc089db6df322bb2df9444](https://github.com/Globox1997/AdventureZ/commit/f6c3d71e08e646cc04dc089db6df322bb2df9444)^^
But yours looks a little better :D

**Comment by CCCClear** [comment]
Oh, I just found out about this texture update, I think we have similar ideas based on the colors
I love this mod so much that I wanted to share some of my little ideas
Your update speed makes me very happy, please don't mind these little things :D

**Comment by Globox1997** [comment]
Hehe, we definitely had the same idea^^ 
Always open for ideas :) Which one of your textures do you prefer? If you allow me to use one of course

**Comment by CCCClear** [comment]
That's great! I prefer the sealed one
Who wants to be stared at all the time by a book? ᐇ

**Comment by Globox1997** [comment]
do you allow me to use it? :)

**Comment by CCCClear** [comment]
Of course

**Comment by Globox1997** [comment]
thank you :) do you have discord?^^

**Comment by CCCClear** [comment]
Emmmmmm...I hardly ever use these social apps 
Never mind, I'll just keep following your mods

**Comment by Globox1997** [comment]
Alright :) I just use it as a forum to talk about mods^^ Thanks again for the drawing, gonna implement it soon

**Comment by Globox1997** [comment]
Added your texture :) [https://github.com/Globox1997/AdventureZ/commit/b3b75485269f8b45d3cc1547834262ad04934aa8](https://github.com/Globox1997/AdventureZ/commit/b3b75485269f8b45d3cc1547834262ad04934aa8)
