### ISSUE TITLE
[SUGGESTION] Wiki

### ISSUE THREAD

**Issue by srnyx** [Globox1997/AdventureZ#29]
Create a wiki for the mod like you did for all your other mods.

**Comment by Globox1997** [comment]
Do you mean the wiki on the github website?
It was basically a fun project where I don't have any plans to develop it further.
The modpage on curseforge should have enough information about my mods, everything else can get explored or people can ask others on the discord for example :)

**Comment by srnyx** [comment]
> Do you mean the wiki on the github website?


> Do you mean the wiki on the github website?

No the wiki on the ModZ website 

> It was basically a fun project where I don't have any plans to develop it further.

Wait so you don't plan to update AdventureZ anymore?

**Comment by Globox1997** [comment]
No I'm talking about the wiki page.
AdventureZ will have updates still

**Comment by srnyx** [comment]
> No I'm talking about the wiki page.
> AdventureZ will have updates still

Oh, ok, phew, I was a bit worried there. lol
I think that wikis are usually really helpful when it comes to mods. Even if it's just an FAQ section, it'll still help answer questions that will make using the mod more understandable.
The main reason why I wanted a wiki was that I don't know how to get half of the items in the game (specifically the Prime Eye [a friend told me how to get it]). And it'd be pretty annoying to have to ask in the Discord for each item I have a question about.

**Comment by Globox1997** [comment]
I understand but for this reason I added a handbook to adventurez via patchouli mod :)

**Comment by srnyx** [comment]
> I understand but for this reason I added a handbook to adventurez via patchouli mod :)

Ohhhhhh, alright, that's perfect then, I'll use that. I didn't know there was one, sorry.

**Comment by Globox1997** [comment]
No problem^^ I will probably update the mod page to give a little bit more information when I have enough time
