### ISSUE TITLE
Orcs don't drop orc skin/leather

### ISSUE THREAD

**Issue by varencilator** [Globox1997/AdventureZ#30]
Orcs don't drop orc skin/leather. Killed many with Looting 50 and didn't get anything except experience and other items from a different mod (Composing).

**Comment by Globox1997** [comment]
Yes, latest version has no loot table cause I forgot to change the existing one, will be fixed in the next update

**Comment by varencilator** [comment]
Cool looking forward to the update!

**Comment by superon** [comment]
lawks was going to say the similar...  looks like it has a lot table but it's listed as "ork" instead of "orc"   easily fixed user-end by adding this to entities loot and changing the name :)

**Comment by varencilator** [comment]
Build 1.2.3 loot tables are fixed
