### ISSUE TITLE
Kicked from the server while riding a dragon

### ISSUE THREAD

**Issue by AlltosSoul** [Globox1997/AdventureZ#31]
I get kicked from the server and it says "Flying is not enabled on this server"

**Comment by AlltosSoul** [comment]
ok

**Comment by Globox1997** [comment]
I guess this fixed your problem?

**Comment by Globox1997** [comment]
In the next version you don't have to enable the flight property [https://github.com/Globox1997/AdventureZ/commit/6ffa16dc82029a1d83a21cda866a530975ba8583](https://github.com/Globox1997/AdventureZ/commit/6ffa16dc82029a1d83a21cda866a530975ba8583)
