### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by lilPNUTTY** [Globox1997/AdventureZ#33]
I don't know why but all entities have the same sound volume regardless of distance so orcs on the surface sound like they are right next to me if I was in a cave.

**Comment by Globox1997** [comment]
Most of them yes, is fixed in the coming update :)

**Comment by Globox1997** [comment]
Fixed in version 1.2.3

**Comment by lilPNUTTY** [comment]
Thank god this was bugging me for a while!
