### ISSUE TITLE
Server crashes on startup [v1.2.3]

### ISSUE THREAD

**Issue by srnyx** [Globox1997/AdventureZ#35]
The server crashes on startup when using `v1.2.3`, `v1.2.2` works fine.
`latest.log`: https://paste.srnyx.xyz/kopuxelufo.pl

**Comment by Globox1997** [comment]
In v1.2.3 I added the config for generating dragon eggs every time you kill a dragon and the mod UnlimitedDragonEggs does the same thing but it uses an Overwrite which makes it incompatible with every mod which tries to inject code in the same method (Overwrites are very simple to code but very bad for compatibility)

**Comment by Globox1997** [comment]
I won't change anything because from my side, it is 100% compatible. I would recommend to ask the dev of unlimited dragon eggs to change his overwrite to a simple inject method or you have to decide which mod you want and remove the other one

**Comment by srnyx** [comment]
> In v1.2.3 I added the config for generating dragon eggs every time you kill a dragon and the mod UnlimitedDragonEggs does the same thing

Ohhhhh, I'll just remove UnlimitedDragonEggs then. This is perfect cause it'll let me remove another mod off my server haha

**Comment by Globox1997** [comment]
I guess I can close the issue now :)
