### ISSUE TITLE
crasht

### ISSUE THREAD

**Issue by ShadowSlayerFX1** [Globox1997/AdventureZ#36]
---- Minecraft Crash Report ----
// You're mean.

Time: 31-5-21 17:26
Description: Exception in server tick loop

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_3218.<init>(class_3218.java:209)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:410)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:335)
	at net.minecraft.class_1132.method_3823(class_1132.java:86)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$9064/535835380.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [adventurez.mixins.json:EnderDragonFightMixin] from phase [DEFAULT] in config [adventurez.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 14 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_2881::dragonKilledMixin with priority 1000 cannot inject into net/minecraft/class_2881::method_12528(Lnet/minecraft/class_1510;)V merged by ido.unlimiteddragoneggs.mixin.EnderDragonFightMixin with priority 1000 [PREINJECT Applicator Phase -> adventurez.mixins.json:EnderDragonFightMixin -> Prepare Injections ->  -> handler$cno000$dragonKilledMixin(Lnet/minecraft/class_1510;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 12945639832 bytes (12345 MB) / 16106127360 bytes (15360 MB) up to 16106127360 bytes (15360 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adabraniummod: Adabranium 1.4.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		advancementinfo: AdvancementInfo 1.16.5-fabric0.30.0-1.2
		adventurez: AdventureZ 1.2.3
		alaskanativecraft: Alaska Native Craft 1.2.0
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin 1.0.11
		aquarius: Aquarius 1.0.3
		arcanaflavor: Arcana Flavor 0.0.8+1.16-alpha
		architectury: Architectury 1.10.139
		armorstandutils: Armor Stand Utils 1.0.1
		artifacts: Artifacts 3.2.1+fabric
		artifice: Artifice 0.13.2+1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		backslot: BackSlot 1.1.11
		backslotaddon: BackSlot Addon 1.0.3
		banner_capes: Banner Capes 0.2.1
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		bettereating: Better Eating 0.3.0
		betterend: Better End 0.9.6-pre
		betternether: Better Nether 5.0.7
		biomeinfo: Biome Info 1.16.5-6
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blast: BLAST 1.5.2
		blastingsand: Blasting Sand 1.16.5
		blockus: Blockus 2.1.4+1.16.5
		blue_endless_jankson: jankson 1.2.0
		boot: BootZ 1.3.5
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.0.2-1.16.5
		bundlesplus: bundles plus 0.1.8
		byg: BYG 1.1.8
		caelus: Caelus API 0.0.15-1.16.4
		cardinal-components: Cardinal Components API 2.7.13
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.7.13
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.13
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.7.13
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.13
		cardinal-components-util: Cardinal Components API (utilities) 2.7.13
		cardinal-components-world: Cardinal Components API (worlds) 2.7.13
		cauldronoverhaul: Cauldron Overhaul 2.0.0
		chainmailrecipefabric: ChainmailRecipeFabric 1.0.0
		chesttracker: Chest Tracker 0.8.13
		chillager_mod: Chillager 1.1
		cloth-api: Cloth API 1.2.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.15
		cobblefish: Cobblefish Mod 2.0.0
		compactstatuseffects: Compact Status Effects 1.2.3
		conjuring: Conjuring 0.1.7
		convenient-mobgriefing: Convenient mobGriefing 1.1.4
		cosmetic-armor: Cosmetic Armor 1.0.0
		creativekeybind: CreativeKeybind 1.0.1
		crowdin-translate: CrowdinTranslate 1.2
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.10-1.16.3
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		curiousshulkerboxes: Curious Shulker Boxes 1.1.1-1.16.5
		customportalapi: customportalapi 0.0.1-beta18-1.16
		dark-enchanting: Dark Enchanting 0.1.1+mc.1.16.5
		deadlydaggers: DeadlyDaggers 1.0-1.16.5
		decorative: Decorative 4.0.0
		dehydration: Dehydration 1.1.4
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		doublejump: Double Jump Mod 1.16.1-1.0.0
		dragonloot: DragonLoot 1.0.6
		dropspread: Drop Spread 1.0
		dualwielding: Dual Wielding 1.0.2
		durabilityviewer: Giselbaers Durability Viewer 1.16.5-fabric0.30.0-1.10
		earthtojavamobs: Earth2Java 1.7.1+1.16.4
		eggtab: Egg Tab 1.3.2+1.16-fabric
		enchant_giver: Enchant Giver 1.0.3
		enchantedtooltips: Enchanted ToolTips 1.3.4-1.16
		enchants: Enchants Plus 1.0.0
		enderitemod: Enderite Mod 1.2.2
		endreborn: End: Rebellion 1.8
		enhancement: Enhancement (Fabric) 0.6.0
		environmentz: EnvironmentZ 1.1.1
		equip: EquipZ 1.6.2
		extraalchemy: Extra Alchemy 1.4.4
		fabric: Fabric API 0.33.1+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.5.0+kotlin.1.4.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.11.3
		fantasycraft: Fantasycraft 1.1.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		fluidpotions: Fluid Potions 1.1.4
		foodmodplus: Food Mod Plus 1.0-SNAPSHOT
		gateofbabylon: Gate Of Babylon 1.4.1-1.16.5
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.31
		gg_enchantments: Good Game Enchantments 1.1.1
		go-fish: Go Fish 1.2.1-beta-1.16.4
		gobber2: Gobber2 2.3.71
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		impersonate: Impersonate 2.1.0
		inventoryhotswap: Inventory Hotswap 1.0
		invo: FriendZ 1.5.5
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kibe: Kibe 1.2-BETA
		kyrptconfig: Kytpt Config 1.1.4-1.16
		lavasponge: Lava Sponge 1.0.1
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		libstructure: LibStructure 1.5
		luckyblocks: Fabricated Lucky Blocks 1.0.0-1.16.5
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		mcda: MC Dungeons Armors 1.4.5
		mcdar: MC Dungeons Artifacts 1.1.2
		mcdw: MC Dungeons Weapons 3.1.4
		mcsa: MC Story Mode Armor 2.2.1
		mdg: mdg 1.0.0
		medievalweapons: Medieval Weapons 1.1.1
		mermod: Mermod 1.4
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		mi: More Ice Mod 1.0.0
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		mo_glass: Mo Glass 1.5-MC1.16.5
		mobz: MobZ 2.4.6
		modmenu: Mod Menu 1.16.8
		moenchantments: Mo'Enchantments 1.15.0
		morebakedfoods: More Baked Foods 1.1.0
		moreblocksmod: More Blocks Mod 0.1.4
		morepotions: More Potions 1.0.0
		moretotems: More Totems 2.7.3
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mtca: More Totems Curios Addon 1.0.0
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		musica: Musica 1.3.2
		mutuality: Mutuality 1.0.0
		mycommands: MyCommands Fabric 1.16.1-17
		nbtcrafting: NBT Crafting 2.0.3+mc1.16.4
		netherite_nugget: Netherite Nugget 1.2.1
		netherite_plus: Netherite Plus Mod 1.1.0
		netherited: Netherited 0.9.1
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		netheritems: Nether Items 1.1.0
		nicephore: Nicephore fabric-1.16.x-1.1.5
		omega-config: OmegaConfig 1.0.4
		opitems: Op Items 1.1.0
		optifabric: OptiFabric 1.9.6
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.1.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.1.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 1.9.0+21w10a
		pigsteel: Pigsteel Mod 1.4.0
		playerabilitylib: Pal 1.2.1
		potiondescriptions: Potion Descriptions fabric-1.1
		potionofbees: Potion Of Bees 1.0.2
		pptowers: Pew Pew Towers 1.0.2
		prone: prone 0.1.1
		pugh_lib: Pugh Lib 1.1.0
		quiver: Quiver 2.16.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		recently_used: Recently Used 0.2.2+1.16.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		rotten: FleshZ 1.3.0
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		sculkconcept: Sculk beta-0.1.0
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		shulkerutils: shulkerutils 1.0.1-1.16
		simply_tomato: Simply Tomatoes 1.0.0
		slime_sling: SlimeSling 1.0.0
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		somnus: Somnus API 0.0.11-1.16.5
		spellbound: Spellbound 1.2.1
		spoornloot: SpoornLoot 1.10.4
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.1.0
		structure-helpers: Structure Helpers 3.0.0
		stuffz: StuffZ 2.2.5
		telekinesis: Telekinesis Enchantment 1.1.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		things: Things 0.1.2
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		tooltipfix: ToolTip Fix 1.0.2-1.16
		tooltiprareness: Tooltip Rareness 1.0.0
		torohealth: ToroHealth Damage Indicators 1.16.4-fabric-3
		transportables: Transportables 1.0.1
		trapexpansion: Trap Expansion 1.3.2
		tridentfixer: Repairable Tridents 1.0.0
		trinkets: Trinkets 2.6.7
		ultra_amplified_dimension: Ultra Amplified Dimension 1.16.4-9.1.1-fabric
		unlimiteddragoneggs: Unlimited Dragon Eggs 1.1.1
		unsaddlepigs: Unsaddle Pigs 1.2-mc1.16.4-fabric
		untitledduckmod: Untitled Duck Mod 0.2.1
		upgradedechests: Upgraded Ender Chests 1.0.1-1.16
		vafoen: Vanilla Food Enhanced 1.1.1
		vanillarubies: Vanilla Rubies 1.0.1
		voidz: VoidZ 1.0.0
		voxelmap: VoxelMap 1.10.15
		voyager: Voyager 1.0.0
		whereisit: Where Is It 1.11.7
		wi_zoom: WI Zoom 1.3-MC1.16.5
		witherite: Witherite 0.0.3
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		xaerominimap: Xaero's Minimap 21.4.2
		xaeroworldmap: Xaero's World Map 1.13.4
		xenchant: xenchant 1.0.3
		xp_storage: XP Storage 1.4+1.16.5
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	OptiFine Version: OptiFine_1.16.5_HD_U_G7
	OptiFine Build: 20210219-144623
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Enhanced Default v1.11.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.5
	OptiFine jar version: OptiFine_1.16.5_HD_U_G7
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: F:\.minecraft\.optifine\OptiFine_1.16.5_HD_U_G7\Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by Globox1997** [comment]
Thanks for the report, it is the same issue as with #35 , unlimited dragon egg mod overwrites a method where Adventurez injects code into. please send the crash log via a paste site next time ;)
