### ISSUE TITLE
Crash with Unlimited Dragon Eggs

### ISSUE THREAD

**Issue by PalgamingHD** [Globox1997/AdventureZ#38]
Game crashes with the unlimited dragon eggs, which is kinda necessary for multiple eye fights

**Comment by Globox1997** [comment]
Same issue as #36 and #35 ;)
unlimited dragon egg mod overwrites a method where Adventurez injects code into. so there won't be compatibility as long as unlimited dragon egg mod tries to make itself compatible with any mod.
there is a config setting to allow multiple dragon egg drops in the latest version
