### ISSUE TITLE
Source Stone teleport ability ignores Flan claims

### ISSUE THREAD

**Issue by srnyx** [Globox1997/AdventureZ#40]
https://github.com/Globox1997/VoidZ/issues/6

**Comment by Globox1997** [comment]
How does the flan mod work? 
If some area is claimed, you need permission to walk on it or you can not open doors for example?

**Comment by srnyx** [comment]
If some area is claimed, you need permission to walk on it or you can not open doors for example?

Yeah. But permission can be set per-claim by the claim owner.

**Comment by Globox1997** [comment]
what does happen if you try to move onto the claimed ground?

**Comment by srnyx** [comment]
> what does happen if you try to move onto the claimed ground?

Nothing happens when normally walking on the claim's ground. But it's still possible to shift-right click phase through blocks inside the claim. So if there is a base there, people can use it to get inside.

**Comment by Globox1997** [comment]
Added a config to disable porting via the source stone to avoid this issue. May add compat in a future update
