### ISSUE TITLE
Hitting a player or a mob with a boulder crashes server

### ISSUE THREAD

**Issue by KatelynnChan** [Globox1997/AdventureZ#42]
So im using BetterMinecraft[fabric] modpack and when the stone golem throws its rock at a mob or a player it crashes the server. This is hosted in a apex server 5gb ram. The crash log is 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 6/15/21 4:07 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.adventurez.entity.nonliving.ThrownRockEntity.method_7495()Lnet/minecraft/class_1799;
	at net.adventurez.entity.nonliving.ThrownRockEntity.method_7454(ThrownRockEntity.java:100)
	at net.minecraft.class_1676.method_7488(class_1676.java:118)
	at net.adventurez.entity.nonliving.ThrownRockEntity.method_7488(ThrownRockEntity.java:68)
	at net.minecraft.class_1682.method_5773(class_1682.java:67)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.adventurez.entity.nonliving.ThrownRockEntity.method_7454(ThrownRockEntity.java:100)
	at net.minecraft.class_1676.method_7488(class_1676.java:118)
	at net.adventurez.entity.nonliving.ThrownRockEntity.method_7488(ThrownRockEntity.java:68)
	at net.minecraft.class_1682.method_5773(class_1682.java:67)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: adventurez:thrown_rock (net.adventurez.entity.nonliving.ThrownRockEntity)
	Entity ID: 1341
	Entity Name: entity.adventurez.thrown_rock
	Entity's Exact location: 90.96, 58.00, 95.71
	Entity's Block location: World: (90,58,95), Chunk: (at 10,3,15 in 5,5; contains blocks 80,0,80 to 95,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.13, -0.29, -0.21
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_3222['KatelynnChan'/574, l='ServerLevel[world]', x=90.35, y=56.74, z=95.03]]
	Chunk stats: ServerChunkCache: 2496
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,70,209), Chunk: (at 0,4,1 in 8,13; contains blocks 128,0,208 to 143,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 273501 game time, 273501 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 3.10.0-1160.21.1.el7.x86_64
	Java Version: 1.8.0_292, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Red Hat, Inc.
	Memory: 1332171432 bytes (1270 MB) / 3489660928 bytes (3328 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 16
	JVM Flags: 20 total; -Xmx5120M -Xms3328M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.3.11
		adventurez: AdventureZ 1.2.4
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antiqueatlas: Antique Atlas 5.4.4-fabric
		architectury: Architectury 1.17.20
		armourtoughnessbar: ArmourToughnessBar 1.0.2
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		backslot: BackSlot 1.1.11
		beaconoverhaul: Beacon Overhaul 1.3.0+1.16
		bedspreads: Bedspreads 1.3.1-1.16.4
		beholdersbookshelves: Beholder's Bookshelves 0.1.1
		beholdersvariations: Beholder's Variations 0.5.5
		better_withered_mobs: Better Withered Mobs 1.5.2
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.6-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.0
		bigbeacons: Big Beacons 1.1.1
		biome_locator: Biome Locator 1.1.2
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.1.1-1.16.5
		brazier: Brazier 3.0.8
		brokennametags: Broken Name Tags 1.0.1
		byg: BYG 1.1.8
		caelus: Caelus API 0.0.15-1.16.4
		campanion: Campanion 1.3.5
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		carrier: Carrier 1.7.6
		cavebiomes: Cave Biomes 0.6.2
		celib: Celib - CebbyS Library Mod 0.4.0
		chillager_mod: Chillager 1.1
		cinderscapes: Cinderscapes 1.3.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.26
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.2.1
		club_minnced_discord-webhooks: discord-webhooks 0.5.6
		colytra: Colytra 1.3.0-1.16.4
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_github_mouse0w0_fastreflection: FastReflection 1.0.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.14.9
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		comforts: Comforts 0.0.3-1.16.5
		complete_bone_meal: Complete Bone Meal 1.1.0
		consistency_plus: Consistency Plus 0.3.0
		cookiecore: Oreo Core 0.0.4
		couplings: Couplings 1.3.3
		crimsonmoon: Crimson Moon 2.0.4-1.16.5
		croptopia: Croptopia 1.4.0
		crowdin-translate: CrowdinTranslate 1.3+1.16
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		customportalapi: Custom Portals 0.0.1-beta32-1.16
		customstars: Custom Stars 0.5
		dark-enchanting: Dark Enchanting 0.2.1+mc.1.16.5
		dawn: Dawn API 1.8
		deep-dungeons: Deep Dungeons 1.0.0-1.16.5
		desolation: Desolation 1.1.1
		dragonloot: DragonLoot 1.0.6
		dual_riders: DualRiders 1.0.5
		earthtojavamobs: Earth2Java 1.7.1+1.16.4
		economical_villager_trading: Economical Villager Trading 1.2+MC1.16.4-1.16.5
		elementalcreepers: Elemental Creepers: Refabricated 1.3.0
		enderporter: Enderporter 1.0.2
		enhanced_mushrooms: Enhanced Mushrooms 1.0.4
		fabric: Fabric API 0.34.6+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabrication: Fabrication 1.3.4
		fabricloader: Fabric Loader 0.11.3
		fallingtree: FallingTree 2.11.4
		fatxporbs: Fat Experience Orbs 0.0.9
		fdlink: Fabric <-> Discord Link 0.9.0
		fdlink_1_12_2: Fabric <-> Discord Link 0.9.0
		fdlink_1_15_2: Fabric <-> Discord Link 0.9.0
		fdlink_1_16: Fabric <-> Discord Link 0.9.0
		fdlink_1_7_10: Fabric <-> Discord Link 0.9.0
		fdlink_1_8_9: Fabric <-> Discord Link 0.9.0
		fdlink_api: Fabric <-> Discord Link API 0.1.0
		fdlink_common: Fabric <-> Discord Link 0.9.0
		fiber: fiber 0.23.0-2
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flytre_lib: FlytreLib 0.2.11
		frozenup: Frozen-Up-Fabric 1.16.5-1.0.0
		geckolib3: Geckolib 3.0.36
		gentlefawn: GentleFawn 1.1.4-MC1.16.5-fabric
		gildednetherite: Gilded Netherite 1.0.0
		glimmeringpotions: Glimmering Potions 1.1.3-1.16.5
		go-fish: Go Fish 1.2.3-beta-1.16.5
		goldenhoppers: Golden Hoppers 1.0.2
		grass_pass: Grass Bypass 1.0.0
		greater_eye: Greater Eye of Ender 1.1.5
		harvest: Harvest 1.2.12
		heartbond: Heartbond 1.0.0
		herdspanic: Herds Panic 1.0.1
		homecamp: Home Camp 1.0.3
		invisframes: Invisible Frames 2.0.1
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 8
		kiln: Kiln 1.1.1+1.16.5
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 3.4.0+1.16.5
		libstructure: Libstructure 1.3
		lithium: Lithium 0.6.4
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		mi: More Ice Mod 1.0.0
		minecraft: Minecraft 1.16.5
		mobz: MobZ 2.4.6
		mooblooms: Mooblooms 1.4.0
		morebookshelves: Bookshelving 0.1.0
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.3-1.16.3
		morerespawnanchors: More Respawn Anchors 1.0.1
		moretotems: More Totems 2.7.3
		morevillagers-fabric: MoreVillagersFabric 1.3.0-SNAPSHOT
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mtca: More Totems Curios Addon 1.0.0
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		net_dv8tion_jda: JDA 4.2.1_255
		net_sf_trove4j_trove4j: trove4j 3.0.3
		netheritems: Nether Items 1.1.0
		new_buckets: New Buckets 1.0.1
		npcvariety: NPC Variety 1.2.4
		omega-config: OmegaConfig 1.0.4
		onsoulfire: On Soul Fire 1.16.5-2
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_apache_commons_commons-math3: commons-math3 3.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
		org_json_json: json 20210307
		org_pircbotx_pircbotx: pircbotx 2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		oro_config: OroArmor Config 1.2.0
		patchouli: Patchouli 1.16.4-51-FABRIC
		phosphor: Phosphor 0.7.2+build.12
		pigsteel: Pigsteel Mod 1.4.0
		playerabilitylib: Pal 1.2.1
		polymorph: Polymorph 0.0.10-1.16.5
		portaltags: Portal Tags 2.1.0
		pride: Pride Lib 1.0.0+1.16
		promenade: Promenade 2.0
		quartzelv: Quartz Elevator 1.2.1
		randompatches: RandomPatches 2.4.5-fabric
		rare-ice: Rare Ice 0.2.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		reroll: Reroll 1.2.1-1.16.5
		roughlyenoughitems: Roughly Enough Items 5.12.235
		roughlyenoughitems-api: REI (API) 5.12.235
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.235
		roughlyenoughitems-runtime: REI (Runtime) 5.12.235
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		seasons: Fabric Seasons 1.2-BETA
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerutils: shulkerutils 1.0.1-1.16
		simple_backpack: SimpleBackpack 1.0.38
		simplexterrain: Simplex Terrain 0.7.2
		simplyimprovedterrain: Simply Improved Terrain 0.3.2.1-Fabric
		skinnedlanterns: Skinned Lanterns 1.16.5-1.1.3
		smoothboot: Smooth Boot 1.16.5-1.6.0
		somnus: Somnus API 0.0.11-1.16.5
		spoornbountymobs: SpoornBountyMobs 1.0.7
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.2.1
		stonetotools: StoneToTools 1.0.0
		strangeberry: Strange Berries 1.2.0
		stuffz: StuffZ 2.3.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrarianslimes: Terrarian Slimes 1.0.3-BETA
		terrestria: Terrestria 2.2.0
		the_aether: The Aether 1.16.5-1.4.1
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		totemicoverhaul: Totemic Overhaul 1.1.4
		trade: Trade 1.1.3
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweed: Tweed API 3.0.0-beta.22
		twitchchat: Twitch Chat Bridge 0.10.1b
		ultra_amplified_dimension: Ultra Amplified Dimension 1.16.4-9.1.1-fabric
		untitledduckmod: Untitled Duck Mod 0.2.2
		upgradedechests: Upgraded Ender Chests 1.0.1-1.16
		upgradedshulkers: Upgraded Shulkers 1.0.1-1.16
		vafoen: Vanilla Food Enhanced 1.1.1
		veinmining: Vein Mining 0.0.7-1.16.5
		villagernames: Villager Names 1.6.0
		voicechat: Simple Voice Chat 1.16.5-1.3.12
		voidz: VoidZ 1.0.0
		voyager: Voyager 1.0.0
		wandering_collector: Wandering Collector 1.0.1+mc1.16.5
		waystones: Waystones 1.1.1.1
		wildworld: Wild World 2.0.0+1.16.5
		windchimes: Windchimes 1.1.1
		witherite: Witherite 0.0.3
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		wthit: wthit 2.10.2
		xp_storage: XP Storage 1.4+1.16.5
		yungsapi: YUNG's API 1.16.5-Fabric-5
		zoob: Monster Of The Ocean Depths 3.0.0
	Player Count: 1 / 1337; [class_3222['KatelynnChan'/574, l='ServerLevel[world]', x=90.35, y=56.74, z=95.03]]
	Data Packs: vanilla, Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by Globox1997** [comment]
please update AdventureZ to the latest version :) that should be the fix
