### ISSUE TITLE
Mammoths spawning everywhere in a Terrestria biome.

### ISSUE THREAD

**Issue by githubbingitup** [Globox1997/AdventureZ#43]
When using this mod alongside Terrestria, this was happening in the Lush Redwood Jungle (I removed Terrestria during testing, so thats why you see a different biome now)

But you can see the mobs:
https://i.imgur.com/6elJiSn.png

My FPS was lowered from about 600 to 100 from all of them.

**Comment by Globox1997** [comment]
That is pretty bad but which mod version do you use?
I addition I recommend to cap fps to your screen refresh rate ;)

**Comment by Globox1997** [comment]
Should be fixed in the latest update
