### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Magnetron64** [Globox1997/AdventureZ#44]
Versions:

AdventureZ version - 1.2.7
Minecraft version - 1.17

Description:
The game crashes on startup

Log:
[crash.txt](https://github.com/Globox1997/AdventureZ/files/6709381/crash.txt)

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/AdventureZ/commit/b55db013a3139a09abd4293e8beac0b7264bc3fc](https://github.com/Globox1997/AdventureZ/commit/b55db013a3139a09abd4293e8beac0b7264bc3fc)
