### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by SFINAE695** [Globox1997/AdventureZ#46]
Versions:

AdventureZ version - 1.2.7
Minecraft version - 1.17

Description:
The server crashes on startup

Log:
[crash.txt](https://github.com/Globox1997/AdventureZ/files/6772915/crash.txt)

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/AdventureZ/commit/3d4195d30c0cd1c18136580f5c46bf5eff6d73e4](https://github.com/Globox1997/AdventureZ/commit/3d4195d30c0cd1c18136580f5c46bf5eff6d73e4)
