### ISSUE TITLE
Dragon has no texture

### ISSUE THREAD

**Issue by birdo-birdson** [Globox1997/AdventureZ#47]
The texture for the dragon does not show up. The eyes, mouth, and saddle appear, but the rest of the dragon is pure black.

**Comment by birdo-birdson** [comment]
Upon further testing, I've discovered that this is actually an incompatibility with Canvas. Canvas also causes the Blackstone Golem to show up as textureless, being completely white except for its veins.

**Comment by Globox1997** [comment]
Fixed canvas compat with [https://github.com/Globox1997/AdventureZ/commit/0b7023c95fbe15b73a67bfb091d132521fe142e9](https://github.com/Globox1997/AdventureZ/commit/0b7023c95fbe15b73a67bfb091d132521fe142e9)
