### ISSUE TITLE
Gilded Netherite Fragment doesn't have a tooltip defined in the language file

### ISSUE THREAD

**Issue by RacoonDog** [Globox1997/AdventureZ#48]
Using version 1.2.7 on fabric 1.17 with the "English (US)" language selected

Gilded Netherite Fragment has "item.adventurez.gilded_netherite_fragment.tooltip2" as a tooltip.

**Comment by Globox1997** [comment]
Thanks for report, fixed with [https://github.com/Globox1997/AdventureZ/commit/7d1f84e109448745660ac51ab22b1608b8feef2f](https://github.com/Globox1997/AdventureZ/commit/7d1f84e109448745660ac51ab22b1608b8feef2f)
