### ISSUE TITLE
AdventureZ and VoidZ not compatible with 1.17-1.17.1 server

### ISSUE THREAD

**Issue by DeathStrobe76** [Globox1997/AdventureZ#50]
AdventureZ and VoidZ don't seem to be compatible with my server. It causes the server to crash, but mods work just fine in singleplayer.

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/3d4195d30c0cd1c18136580f5c46bf5eff6d73e4](https://github.com/Globox1997/AdventureZ/commit/3d4195d30c0cd1c18136580f5c46bf5eff6d73e4)
