### ISSUE TITLE
Many spawns

### ISSUE THREAD

**Issue by VoidLock92** [Globox1997/AdventureZ#53]
For some reason I am getting a lot of mammoth spawns in snow biomes with default config settings.
![mammoths](https://user-images.githubusercontent.com/21327041/126033103-c96ef75e-59d4-4d5d-8386-7a297fede9d2.png)

**Comment by Globox1997** [comment]
Which mod version do you use?

**Comment by VoidLock92** [comment]
we are using 'adventurez-1.2.6.jar' in the modpack

**Comment by VoidLock92** [comment]
![image](https://user-images.githubusercontent.com/21327041/126051442-33b747eb-c25b-449f-8c98-59fa656fbb68.png)
Mammoths are using almost 2% of all server performance.

**Comment by Globox1997** [comment]
update to the latest adventurez version, that should fix this

**Comment by VoidLock92** [comment]
Does this version work with 1.16.5 or will I need to wait till I can update the server to 1.17? Version 1.2.7 said it was for version 1.17 of MC. If I need to wait till all other mods are updated to 1.17 its not a big deal just curious as I know forge version and compatibility listings are a bit weird sometimes.

**Comment by Globox1997** [comment]
mh this is actually pretty weird cause since 1.2.5 I fixed the mob spawn bug... 
however, just checked it and the latest version for sure works fine but is only for 1.17
can only support the latest version due to time reasons

**Comment by VoidLock92** [comment]
Turns out this issue also was the cause of a memory leak on the server, I spent a while trying to figure out what was causing the leak. Turns out it is this version of AdventureZ. I really love this mod hoping I can figure out how to keep using it :) After taking out the mod the memory leak is fixed. It might have top do with the mammoths and since you said you fixed this in 1.17 I would assume the issue might be fixed then. I wonder if I could compile a version for 1.16.5 :)

**Comment by Globox1997** [comment]
Just uploaded a new mod version on curseforge :)
Weird that there is a memory leak, if you know where it comes from, would be good to know :D
You can definitely try to compile on for 1.16.5 but it will be hard I guess^^

**Comment by VoidLock92** [comment]
I turned off mammoths in the config and now it seems to be alright so far.

**Comment by Globox1997** [comment]
Should be fixed with the latest update, please reopen if it still happens
