### ISSUE TITLE
AdventureZ chrashes on start without VoidZ

### ISSUE THREAD

**Issue by Taldariner** [Globox1997/AdventureZ#54]
It only happens on 1.17+ version and, as I can understand from crash log, AdventureZ tried to initialize VoidZ dimension on game start, but can't, as I had't installed VoidZ. After it installation, game starts normally.

**Comment by Globox1997** [comment]
Thanks for fast report, fixed with [https://github.com/Globox1997/AdventureZ/commit/08f35efb3622fee4701a1e38cd5365fbb2ba9c59](https://github.com/Globox1997/AdventureZ/commit/08f35efb3622fee4701a1e38cd5365fbb2ba9c59)
