### ISSUE TITLE
1.17.1: AZ makes server freeze indefinitely

### ISSUE THREAD

**Issue by superdumpling** [Globox1997/AdventureZ#55]
Using AZ 1.2.9
Playing singleplayer, not on a server

I did some trial and error debugging and found this mod causes the server side to freeze (blocks don't drop anything, all mobs stop moving, etc) at consistent spots in the nether (I couldn't locate what causes it though, just freezes at consistent random spots). After the server freezes, if I try to exit to menu, it gets stuck on saving world forever and I have to terminate the game with task manager. I also spawned all the AZ mobs in a test world in the nether and nothing happened so I don't know why removing AZ stops the server from freezing at those seemingly random locations

other mods I have that add to nether: [ 5.1.3 Better nether ], [ 0.3.3 wither totems ]
and im also using sodium + iris with a shader enabled

**Comment by Globox1997** [comment]
Thanks for the report :) Fixed with [https://github.com/Globox1997/AdventureZ/commit/8c6fb4a5b0e4ab8edae170a80133845adec40dfc](https://github.com/Globox1997/AdventureZ/commit/8c6fb4a5b0e4ab8edae170a80133845adec40dfc)
