### ISSUE TITLE
Orcs not spawning in plains

### ISSUE THREAD

**Issue by DrakonoSoul** [Globox1997/AdventureZ#57]
Orcs are not appearing in the plains biomes.

I tried increasing the spawn weight from 10 to 50 and they still don't spawn.

The only biome mod I'm using is William Wythers' Overhauled Overworld

**Comment by Globox1997** [comment]
Might be fixed with the latest update :)

**Comment by Globox1997** [comment]
If the biome mod you are using is just adding biomes via a datapack, only vanilla biomes will spawn adventurez mobs btw
