### ISSUE TITLE
Crash in the Nether

### ISSUE THREAD

**Issue by InteJason** [Globox1997/AdventureZ#58]
Version: 1.17.1 
Fabric 0.11.6 
Mod Version: AdventureZ 1.2.11
Crash when loading in a specific part of the Nether dimension
The modpack contains a datapack called 'Incendium' that overhauls the Nether Dimension, think it can be the issue?
https://pastebin.com/3ekPYe7w

**Comment by TheWalrusGamer** [comment]
Same As Above, Going to test in 1.2.9 to see If I can replicate prior to the nether fix.
https://pastebin.com/4piT6UfF

**Comment by TheWalrusGamer** [comment]
The Error Does not occur when playing on a locally hosted server. Seems to be a problem with the implementation on integrated servers while using immersive portals. 
Can replicate, works fine while traveling through the nether, but when generating a stronghold in the nether while traveling in the overworld causes a crash. Error references The Blaze Guardian Placement.
https://pastebin.com/rgi4yj4a

**Comment by Globox1997** [comment]
[adventurez-1.3.0.zip](https://github.com/Globox1997/AdventureZ/files/7188481/adventurez-1.3.0.zip)
Thanks for the report, could one of you check this update out? Unzipping the file necessary

**Comment by TheWalrusGamer** [comment]
Will have a report for ya tomorrow.

**Comment by FIowify** [comment]
Wait so how do I fix this?

**Comment by TheWalrusGamer** [comment]
So, I took a look, same end result. 
https://pastebin.com/CxeHeirP

**Comment by Globox1997** [comment]
But it happens only with the immersive portal mod I guess? Wondering how chunks can get loaded when the player is not in the dimension

**Comment by TheWalrusGamer** [comment]
From what I gather from the github/wiki, the game renders and loads other dimensions & chunks while the player isn't around, and imposes a camera visible through a portal so you can see it.

Also, I read through your code and the crash log again, it seems to crash on trying to spawn the blaze guardian shields into the client thread, which would explain why it doesn't crash on a server. Is it possible to specify spawning it on the server thread? I know the code you have js world.spawnEntity, is there a server.spawnEntity? Or possibly you summon the shields on aggro as a workaround?

**Comment by Globox1997** [comment]
[adventurez-1.3.0.zip](https://github.com/Globox1997/AdventureZ/files/7223361/adventurez-1.3.0.zip)
By your information I looked closer and this may fixes the issue

**Comment by TheWalrusGamer** [comment]
So, I ran the new file, It doesn't seem to fix the crashes, a new log is attached. I'm also going to open an issue on the immersive portals tracker to see if we can get any clarification.
[https://pastebin.com/iWtNJDBm](https://pastebin.com/iWtNJDBm)

**Comment by Globox1997** [comment]
[adventurez-1.3.0.zip](https://github.com/Globox1997/AdventureZ/files/7245268/adventurez-1.3.0.zip)
Maybe you can try out this, it removes the additional entity spawn to the blaze guardian

**Comment by Globox1997** [comment]
[adventurez-1.3.0.zip](https://github.com/Globox1997/AdventureZ/files/7245287/adventurez-1.3.0.zip)
this would be my last idea for a real solution

**Comment by TheWalrusGamer** [comment]
Honestly, No idea what you did to fix it, but the fix worked. It no longer crashes.
Is this version stable, and if not, will there be an update soon?

> 
> 
> [adventurez-1.3.0.zip](https://github.com/Globox1997/AdventureZ/files/7245268/adventurez-1.3.0.zip) Maybe you can try out this, it removes the additional entity spawn to the blaze guardian

**Comment by Globox1997** [comment]
What about the last version I sent? Please try it out too

**Comment by TheWalrusGamer** [comment]
Yup, Both of them work no problem, no errors in the log either

**Comment by Globox1997** [comment]
perfect :D I will leave the issue open until the next version is released
