### ISSUE TITLE
[Bug] Crash on trying to load entity NBT of the Red Fungus

### ISSUE THREAD

**Issue by alexmozaidze** [Globox1997/AdventureZ#59]
The game crashes when it tries to load Red Fungus' NBT. That happened while I was trying to reload resourcepacks, and it hapened before, when I hovered over the spawn egg of Red Fungus with Inspecio mod
Here's the crash log: https://drive.google.com/file/d/1UDSoBZEuHrRCWsMhoSu12KDwqSRC2Dc9/view?usp=sharing

**Comment by FIowify** [comment]
how do we fix it

**Comment by Globox1997** [comment]
Was the same as #60 and fixed with [https://github.com/Globox1997/AdventureZ/commit/7d1841ce9350be63b58184a26ded35db511ed2f0](https://github.com/Globox1997/AdventureZ/commit/7d1841ce9350be63b58184a26ded35db511ed2f0)
