### ISSUE TITLE
Crash With Inspecio

### ISSUE THREAD

**Issue by Pop000100** [Globox1997/AdventureZ#60]
They say its on your side.

https://github.com/Queerbric/Inspecio/issues/33

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/7d1841ce9350be63b58184a26ded35db511ed2f0](https://github.com/Globox1997/AdventureZ/commit/7d1841ce9350be63b58184a26ded35db511ed2f0)
Thanks for reporting :)
