### ISSUE TITLE
Stone Golem Heart suggestions

### ISSUE THREAD

**Issue by Kiryonn** [Globox1997/AdventureZ#61]
![blackstone golem heart](https://user-images.githubusercontent.com/60699390/136829645-42f92df1-2442-455f-b94f-bf47f3e311bd.png)
So i was thinking that this item was way to good to be limited to the making of a weapon
No seriously did you heard that sound when it's in your inventory ??? JUST GOLD !!!

## FRIENDLY GOLEM
Iron golems are great. They protect your villagers and kill most of your enemies. BUT for players like me that play in hard difficulty, since there is a lot more and stronger mobs, the iron golems get destroyed before the end of a night. And what they leave behind is an army of creepers (since they killed other mob types). And that is not good. every corner, a creeper, and when it's not, you have to fight a dozen of them at the same time while trying to prevent the land from being damaged.

Which is why i want a stronger golem. of course, not in the full power like he is in boss form. but i thought that maybe having the possibility to "tame" the stone golem would be good for that.

### TAMING

After having fought for a long time, the adventurer gave his opponent a hand, letting him the choice to follow him. Since the human almost destroyed the golem heart, he decided to give him a new one. A new heart, a new life.
![image](https://user-images.githubusercontent.com/60699390/136824809-757b25d5-a3cb-445d-85bf-7c3a4060655f.png)

When below 50hp, giving the Stone Golem Boss a golem heart will heal him and get him friendlier

Having left behind his Boss status, he'll be weaker, but still stronger than your average iron golem. Also he will attack all hostile mobs, including creepers. Of course, if you hit him, he will hit you back (resetable with time or player death).

### REPAIRING

Since iron golems can be repaired with iron, i figured it would be logic if the stone golem get repaired with either blackstone, gilded blackstone, gilded blackstone shard, or blackstone golem heart.

My best suggestion is that it will heal depending on what you used.
| IMAGE | ITEM | HEALTH |
| :---: | :--- | :---: |
|![blackstone](https://user-images.githubusercontent.com/60699390/136827737-aadc9f43-c15e-481c-89fa-76fca4c2b187.png)| blackstone | 10 |
|![gilded blackstone](https://user-images.githubusercontent.com/60699390/136828230-af24804a-4686-41db-96a2-d83fbdd8a166.png)| gilded blackstone | 50 |
|![gilded blackstone shard](https://user-images.githubusercontent.com/60699390/136829090-d485bfab-0b6a-47ba-b0a4-74fa3aeac01e.png)| gilded blackstone shard | 20 % |
| ![blackstone golem heart](https://user-images.githubusercontent.com/60699390/136829645-42f92df1-2442-455f-b94f-bf47f3e311bd.png) | blackstone golem heart | 75% |

## GET RID OF YOUR HUMANITY

Knowing what you will have to face, you made the decision to loose your humanity. You activate the heart that turns blue, the heartbeats are louder and faster as time pass. When it's finished, you feel weird, but powerfull. Your heart is stronger, it is no longer the time to doubt. Your enemies awaits you.
![image](https://user-images.githubusercontent.com/60699390/136831969-9faa0066-81ed-441f-ad82-8cc9b764597c.png)

I thought that it would be cool to strengthen your heart with it. It would give you a bit more stats. maybe +4 health (♥♥) and +1 attack damage.
Of course it will not be cumulable.

**Comment by Globox1997** [comment]
https://user-images.githubusercontent.com/55102939/136955504-66cd6512-4474-48ef-8c25-76ec1143ef59.mp4
