### ISSUE TITLE
Left clicking dragon egg in the void sometimes causes the dragon egg to be lost

### ISSUE THREAD

**Issue by ChadIImus** [Globox1997/AdventureZ#62]
After defeating the void shadow in the void and left clicking the dragon egg, the egg will attempt to move, one possibility is under the boss arena, making it inaccessible. 

Version: better minecraft (fabric), which i think should be 1.3.0.

Suggestion: Put the egg in the reward chest instead, it is needlessly confusing to suddenly be able to pick it up with right click. The platform could also be make bigger so that the egg won't go under it.

**Comment by Globox1997** [comment]
Added the dragon egg to the loot box of the void shadow with [https://github.com/Globox1997/AdventureZ/commit/b247a43019c43f39d0409ee9048fbd9e46cf062b](https://github.com/Globox1997/AdventureZ/commit/b247a43019c43f39d0409ee9048fbd9e46cf062b)
