### ISSUE TITLE
Source Stone crashing people when hit by projectile

### ISSUE THREAD

**Issue by red2blue** [Globox1997/AdventureZ#67]
https://paste.corebot.dev/okolegoced.md 

Latest version

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/AdventureZ/commit/53a6a496ad9e4597eb78c418e52d4ea91fd80d12](https://github.com/Globox1997/AdventureZ/commit/53a6a496ad9e4597eb78c418e52d4ea91fd80d12)
