### ISSUE TITLE
Orcs Won't Spawn

### ISSUE THREAD

**Issue by skatemo** [Globox1997/AdventureZ#68]
while using this mod in a PwrDown RPG modpack, Orcs wouldn't spawn even after significantly increasing the spawn weight so I tried manually spawning one in via spawn egg in creative.. when I tried to spawn it in with the egg the Orc would flash on the screen and despawn and the texture appearing on the minimap/hud mod has no texture for the orcs at all but instead shows the pink and black texture before the Orc despawns

**Comment by skatemo** [comment]
I believe the only biome mod I am using is Terralith

**Comment by Globox1997** [comment]
Hey skatemo,
is there anything in the server log for spawning the orc with a spawn egg or summon command?
Terralith's biomes aren't compatible with adventurez spawns cause it is made via a datapack (might work in coming 1.18 biome api but who knows), Orcs should spawn then only in vanilla plains biome

**Comment by skatemo** [comment]
Easiest bug fix ever, took the game out of peaceful mode 😂 my apologies
for the miscommunication, I will close the github issue asap
