### ISSUE TITLE
Blackstone Golem [Feature Request & "Bug" Report]

### ISSUE THREAD

**Issue by wolfkidsounds** [Globox1997/AdventureZ#69]
Hey, the following things I noticed when playing with the AdventureZ mod.

- The Blackstone Golem Heart is given as "Effect"
- Drinking Milk removes the Effect permanently again
- Same thing using the "Bed Benefits" mod (sleeping removes status effects)

Feature Request:
- It would be really nice if we could adjust the amount of hearts given by the blackstone golem heart (via config or datapack maybe)

**Comment by Globox1997** [comment]
the blackstoned effect is intentionally an effect.
Added config settings for the effect with [https://github.com/Globox1997/AdventureZ/commit/e87c891b87acaf3bef22a4140b7eb413a83205e1](https://github.com/Globox1997/AdventureZ/commit/e87c891b87acaf3bef22a4140b7eb413a83205e1).
Open for suggestions but the item isn't meant to give the player permanent bonuses

**Comment by wolfkidsounds** [comment]
Thanks - The Lore of the item "swapping it with your own heart" and the way to aquire it just made me think this is intended as a permanent effect.
