### ISSUE TITLE
[1.18] Bad textures?

### ISSUE THREAD

**Issue by mosharky** [Globox1997/AdventureZ#73]
![image](https://user-images.githubusercontent.com/32606683/145352053-8a05300e-0e79-44c6-aaef-dbc02da69eb3.png)

Not sure what could be causing this at all, but I am using Sodium + Iris + Indium, so I assume it's related to that?

**Comment by mosharky** [comment]
This also effects multiple different mobs added by this mod

**Comment by Globox1997** [comment]
If you use Iris, you have to use a shader
