### ISSUE TITLE
Crash on 1.18. GlowingArmorMixin?

### ISSUE THREAD

**Issue by Marius-jj** [Globox1997/AdventureZ#75]
https://pastebin.com/wLimp

renderingGlowingArmorMixin crash?
Started happening after innstalling Iris shader mod, but could be another mod conflict.

Version 1.18
Fabric loader version: 0.12.8-1,18

**Comment by Globox1997** [comment]
Can you repost the crash log?

**Comment by Globox1997** [comment]
Reopen if still existent
