### ISSUE TITLE
AdventureZ Handbook ID not working

### ISSUE THREAD

**Issue by ZomBaeMan** [Globox1997/AdventureZ#79]
Advanced tooltips shows Adventure Handbook id to be "adventurez:adventurez". However, when attempting to use the /give command, this id does not work.
Minecraft Version:1.17.1
Fabric Loader 0.12.12
Fabric Api 0.44.0
AdventureZ 1.4.3
Cloth 5.2.47

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdventureZ/commit/81fe96115d72fc13fa9c1cfe41ea9ee726ab15c4](https://github.com/Globox1997/AdventureZ/commit/81fe96115d72fc13fa9c1cfe41ea9ee726ab15c4)
