### ISSUE TITLE
Suggestion: End (final) Boss : Endfester

### ISSUE THREAD

**Issue by 2Naato** [Globox1997/AdventureZ#8]
- Just finished my answer, looks like I went all out here lmao -  

  

Wow! Quick answer! Thanks! 

Yeah, so I think that there should be another (final) boss in the end for two reasons: 

   **1.** The ender dragon is quite easy to beat (just see speedrunner with beds...): It can be a challenge, that's true, but since there is another boss (the wither) which is harder to beat in my opinion, the ender dragon never felt like a real final boss.. 

   **2.** I always saw it as "one of the two endings possibles": I never liked the idea of having two boss completely separated -> I'd prefer a real - but still very open - progression in the game. That's why I always thought of the ender dragon as the gatekeeper of the end (like you have to beat him to be allowed to really enter the dimension). The real final boss, however, would require the player to actually explore the end (that would be 3. : if the ender dragon is meant to be the final boss, then the end is merely useless considering you have no actual goal left).  

  

  

That's a lot of explanations, I know, but I felt that they were necessary.  

Now that this is done, I did came up with an idea (seems great to me, but I could find as much other ideas as you want, if this one doesn't suit you enough): 

  

I named it: **"The Endfester"** (I also thought of "The Eye" or "The Great Observer"... It's up to you to decide anyway). While designing it, I tried to keep it as simple as I could for a modder. 

  
**Description:** A floating "giant eye of end of ender" mob which mainly shoots explosive laser beams at the player. He's a cosmic entity/a great one (whatever) and the origin/creator of the End dimension (he isn't linked or anything to it tho, so when the player beats it, the end dimension is still there, intact). 

**How to spawn it:** Since I know that you know how to do that, I imagined this: a structure made with a beacon, ether an activated one with the pyramid or at the center of a 5x5 purpur/crying obsidian platform. To spawn the boss, you would need to collect the ender dragon egg (possible with the use of a mod that make the egg respawn each time the dragon is killed in case you lost it), and then place it on the beacon.  

But at this point, you might ask yourself: this method of spawning doesn't require me to explore the end... Just wait a little, I have a solution for that. 

  

**PS:** You would need to be in the end for this to work (note that the Endfester can be spawned anywhere in the end, like the wither or the blackstone golem). 

  

**His look (model/texture/animation):** here I got a few examples from other mods, so that you can clearly visualize the Endfester and take inspiration from it: 

- The "Void eye" from primitive mobs:   [https://www.curseforge.com/minecraft/mc-mods/primitive-mobs] (closest one to how I personnaly see it) 

- The "Ender eye" from grimoire of gaia:   [https://the-grimoire-of-gaia.fandom.com/wiki/Ender_Eye] (The endfester would have no wings in my opinion, like a strange floating alien creature).

- There's even this one from grimoire of gaia too, which looks like a ascended form:   [https://the-grimoire-of-gaia.fandom.com/wiki/Behender] 

So it would look like that, but MUCH bigger (at least 5-6 blocks wide, I would make 9-10 if it was up to me; he got the required space anyway).  

But since he would be a huge mob floating moderately high in the air (see below), and since better end is apparently going to add big-as* trees/ mushroom to the End (so cool!), you'd need to be careful that it does not get obstructed by anything. 

  

**PS:** I realized it later, but the Endfester is quite similar to the Eye of Cthulhu from Terraria, both in appearance and in his way of moving/watching 24h/7 the player.  

Anyway, I think that the model shouldn't be too much of a struggle to make (nor the textures --> a big blocky ender pearl with black eyelids); especially if we take into account the fact that you made all alone every mobs of your mod (they look beautiful)!! 

  

**His AI (and why you would need to explore the End first):** 

- When the egg is placed, the Endfester spawns at the ceiling of the End, then floats down toward the beacon/player (Idk which yet. PS: I imaginated his descent as very menacing and opressing, like a sort of god). After reaching a certain height above the beacon/player, he start attacking. 

- During the fight, the Endfester stays up in the air (high enough for it to be opressing) and is always looking directly at the player. 

- He follows the player, always trying to stay approximatively above him. 

- He can teleport: randomly, and also if the player is hiding or if he is obstructed by something.  

- His primary attack is a laser beam (I don't know exactly how you would do that, but it certainly is doable in minecraft) which he regularly fires at he player: every 10s or so, he charge up the laser for 2-4s making a pre-laser beam (so that the player knows when to quickly dodge), then fires the laser from his pupil. 

Where the laser hits, there would be a relatively small (but not too small) explosion. 

- His secondary attack would be to periodically fire shulker projectiles to the player (I thought that it would be great and easy to make at the same time). 

- He could also try to teleport the player above the void to try to kill him -> to counter this quite unavoidable attack, the player would need elytra (and fireworks), hence the need to explore the end until you find elytras (quite smart actually)! 

- His dying animation could be similar to the ender dragon's one (except for the sound, see below). 

  

**PS:** He could also have a second phase at 50% hp. For example: 

- He could fire lasers/shulker projectiles a bit mod frequently. 

- He could have the ability to teleport the player above the void only during his second phase. 

- He could hover a little higher/lower...  

  

**The sounds he makes:** 

- I had quite the idea there -> he would emit a constent dull sound similar to the one that you hear in movies when there is a scene with a big spaceship, if you now what I'm referring to (a bit like that actually, maybe more intense: [https://www.youtube.com/watch?v=Iv368LFjG7U] ). 

This sound would be stronger as he approaches you -> super opressing, fitting to such a final boss. 

- He could also produce a constent enderman scream (maybe only in the second phase if there is one). 

  

**His drops:** Here, there should be no such thing as a powerfull weapon in my opinion (20+ dmg sword xd...), because 1.you just beat the strongest creature in the game, 2.such equipment is meant to be acquired by mining/processing materials in minecraft and 3.you might be already quite geared up at this point. 

So instead, I just thought of a simple, but very useful item at this stage of the game (plus it's logic): 

  

**"The Prime Pearl"** : Like an ender pearl (more stylish of course hehe), but infinitely reusable (1s cooldown however). It would help travelling, making things faster (pretty much all you might wish for if you continue playing afterwards). 

  

**The stats of the Endfester:** Being the strongest boss of the game, it must be hard to beat (of course, but not impossible too -> minecrafty spirit ya know). 

In term of equipment, it would need AT LEAST full enchanted netherite + elytras + golden apple/carrots. 

Yes, at least, because we do have to keep in mind that playing modded, people will probably have a better equipment (I didn't tested your gilded netherite armor yet, so I can't tell if it's the level of protection I'm thinking of). Here, I'm thinking about the Enderite mod for fabric: 

It would be quite the perfect required equipment being the next stage after netherite, requiring you to explore the end, protecting you from the void and allowing you to attach your elytras to your chestplate! 

So I'm trusting you here (you already proved yourself right on this matter), I just hope that you got my point here. 

  

 

I think that's it, I wrote quite a lot, I hope that it is readable tho! 

So what's your opinion about it? Is it attainable for you?

**Comment by Globox1997** [comment]
That's a big chunk of text, wow :D Love it^^ 
Good story why there is a need for a new boss. Summoning sounds cool but since it is the final fight it may live only once per mc world? :D Or there should be a trigger for spawning this boss. Or it should be really expensive to summon it.

Since I never really got something working with structures, and without it it's hard to implement a good boss fight, the end biome is a really good deal with a flying mob to fight in. It's actually funny but some months ago, a friend of mine had the idea to create something like the Eye of Cthulhu but I actually don't like the design of it cause it looks to disgusting for me (just my personal feel^^)  XD 
Checked those other mobs and they look all great so I'll think about the look of this mob. 
The drops sound good, fits nicely with another idea where you drop a piece of thing with which you can upgrade the gilded netherite armor which allows you to teleport like an enderman. 
Need to think about the ai and sounds are always hard to find :) 
Btw for attaching the elytra to your chestplate there are mods for fabric :D

**Comment by Globox1997** [comment]
![image](https://user-images.githubusercontent.com/55102939/95267907-8fdfd800-0836-11eb-8e14-a5c013dad4dc.png)
playing around with some stuff but haven't got a nice idea yet

**Comment by 2Naato** [comment]
I'm happy that you found my ideas interesting 👍 
So, about his summoning mecanic, I think that my plan of taking a beacon to the end and placing an ender dragon egg is pretty expensive already -> you have to fight both the wither and the Ender dragon each time you want to attempt the fight:
When you die in the end, you respawn in the overworld, so I think that the endfester (or whatever you name it) could despawn (a bit like terraria bosses). In multiplayer, it could for instance search for another target once his first one dies, until there is no potential target left in his vicinity (in which case he despawns after a small delay).

Either that or he could tp to the main island where he could roam, waiting for the player(s) to return.

Oh, and I didn't mentionned it yet, but after his descent above the summoning structure (right after he spawns), the beacon could and the egg could explode (forcing the player to find new ones).
**PS**: I remember that there's a fabric (not totally sure but almost) mod which adds an end structure with a dragon egg inside: it could fit well if it was rare enough, allowing the player to summon the boss without always having to re-summon the dragon.


About the elytras, yes you're right about colytra and curios (the later being my personal favourite). It'll probably be the best solution since better end (definitely gonna include it in my modpack when released) has his own new materials planned (like better nether I guess).
Btw, I don't think that you should worry too much about end mobs (except a boss of course 👌) because better end will probably adds his owns mobs -> it may be better for you if you waited a bit and adapted your work about end mobs based on better end features.

About your model, I think it's a nice potential start (maybe more original than an "ender eye of cthulhu", even if it would _absolutely not_ bother me if it was done this way).
However, I'd make the eye green personaly (like the eye of ender item). I don't know if I would make it 3d (an orb) tho? After all it looks cool how you made it.
Maybe it could be a little less like a flat disc, or even just a blocky eye...

Anyway I like your implication in my little idea 😁 (you even took the time to do a little sketch out of it, thanks!)
If you want other ideas for an end boss, _don't hesitate_ to ask me (or even for another completely unrelated mob, I'd be very happy to reflect about anything if it has a chance to make his way into minecraft!!)

**Comment by Globox1997** [comment]
I actually thought about it a little more and I think I got a cool idea for the design of the mob ;)

So you say the beacon platform should stay but the beacon itself should explode, sounds actually good. 
One of my goals was (or is still) to implement a tameable dragon so idk if the dragon egg fits this summoning event well.
Since the fight is in the end, you have to kill the dragon at least once before summoning this boss except you want a double fight xD 

Even if I wanted to add one or two end mobs, I never got a good idea^^

**Comment by Globox1997** [comment]
I would have an early beta test, do you wanna test it? Its mainly to check the aesthetics and a little bit about the fight mechanic

**Comment by Globox1997** [comment]
Finally I added the end boss I had in mind for the end dimension :) Thanks for the great idea you had even if it differs to my take on it quite a lot
