### ISSUE TITLE
Odd Iris interaction 1.18.1

### ISSUE THREAD

**Issue by RotokEralil** [Globox1997/AdventureZ#81]
Oddest thing; using Iris shader , Three of the mobs skins dont load. Soul Reaper, Blackstone Golem, Nightmare. The rest seem to spawn with no issues. (testesd with Iris [https://www.curseforge.com/minecraft/mc-mods/irisshaders](https://www.curseforge.com/minecraft/mc-mods/irisshaders), its required mods, then without) 
When Iris was removed, no issues with skin.
[https://imgur.com/a/xnqY6pa](https://imgur.com/a/xnqY6pa)

**Comment by Globox1997** [comment]
Mh maybe I should add some config cause those skins don't load when iris without a shader is used

**Comment by Globox1997** [comment]
Changed with [https://github.com/Globox1997/AdventureZ/commit/c14423412a124be9a9e6587c33023f13e2c70a30](https://github.com/Globox1997/AdventureZ/commit/c14423412a124be9a9e6587c33023f13e2c70a30)
