### ISSUE TITLE
Purple texture inside mammoth

### ISSUE THREAD

**Issue by Dejeh** [Globox1997/AdventureZ#84]
AdventureZ v1.4.7

**Comment by Globox1997** [comment]
Can you send a screenshot?

**Comment by Dejeh** [comment]
![2022-01-19_21 28 33](https://user-images.githubusercontent.com/72144320/150261208-304fa408-0e21-4ec7-937c-7974b2473e24.png)

**Comment by Globox1997** [comment]
Thanks, fixed with [https://github.com/Globox1997/AdventureZ/commit/e805344ef8750918a197def6264bb6b09c9b72f4](https://github.com/Globox1997/AdventureZ/commit/e805344ef8750918a197def6264bb6b09c9b72f4)
