### ISSUE TITLE
You can ride baby Nightmares

### ISSUE THREAD

**Issue by Dejeh** [Globox1997/AdventureZ#85]
AdventureZ v1.4.7

**Comment by Globox1997** [comment]
baby nightmares shouldn't obtainable.
Fixed baby riding with [https://github.com/Globox1997/AdventureZ/commit/2a82a0cf6a9c1ac0bb1b0e1cbaf2b6ba9c491c26](https://github.com/Globox1997/AdventureZ/commit/2a82a0cf6a9c1ac0bb1b0e1cbaf2b6ba9c491c26)
