### ISSUE TITLE
Crash on Server

### ISSUE THREAD

**Issue by TheButterbrotMan** [Globox1997/AdventureZ#86]
https://pastebin.com/KgvJSFDz

**Comment by Globox1997** [comment]
[adventurez-1.4.8.zip](https://github.com/Globox1997/AdventureZ/files/7898475/adventurez-1.4.8.zip)
Can you test this for me pls :)

**Comment by TheButterbrotMan** [comment]
Yes

**Comment by TheButterbrotMan** [comment]
My testers are telling me, the portal is (maybe) spawning, but the modpack crashes instantly. 

The mod does not work.

Will attach an crashlog soon

**Comment by TheButterbrotMan** [comment]
Additional, the crashlog seems to blame FTBQuests now. I already opened there are issue some days ago.

https://pastebin.com/FFAdrN8Z

I dont know how to reproduce this poorly. Your fix could helped, but i cant verify.

**Comment by TheButterbrotMan** [comment]
The second crashlog is probably not linked in anyway to the first one, because i had it serveral times, when entering any kind of dimensions.

**Comment by Globox1997** [comment]
Mh it is problematic if it can't get tested...

**Comment by Globox1997** [comment]
Reopen if this still persists in the latest version.
