### ISSUE TITLE
Enchants not working on armor or tools

### ISSUE THREAD

**Issue by TommyInnit4** [Globox1997/AdventureZ#87]
The enchants like Prot 5 or Sharpness 6 aren't working is the something I'm missing for the mod?

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/AdventureZ/commit/8c09f8d4102e8398c819556ef0b48f75acc5b873](https://github.com/Globox1997/AdventureZ/commit/8c09f8d4102e8398c819556ef0b48f75acc5b873)
