### ISSUE TITLE
Riding on Ender whale while server has server property allow-flight=false kicks instantly

### ISSUE THREAD

**Issue by sorat0mo** [Globox1997/AdventureZ#88]
Supposedly this is fixed for Dragon mount, but I still get kicked when riding a whale at the end.

**Comment by Globox1997** [comment]
Thanks for reporting, fixed with [https://github.com/Globox1997/AdventureZ/commit/7279dd3f3de0ff29eff6c2cb7f8d2de03587ee66](https://github.com/Globox1997/AdventureZ/commit/7279dd3f3de0ff29eff6c2cb7f8d2de03587ee66)
