### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by BrokenDawn627** [Globox1997/AdventureZ#89]
[错误报告-2022-2-9_12.10.32.zip](https://github.com/Globox1997/AdventureZ/files/8029858/-2022-2-9_12.10.32.zip)

**Comment by Globox1997** [comment]
When exactly does this happen?
It has to do with the blackstone golem but how can I reproduce this crash?

**Comment by Globox1997** [comment]
Reopen if you have more information about it
