### ISSUE TITLE
Can you make the dragon a tamed mob?

### ISSUE THREAD

**Issue by Dejeh** [Globox1997/AdventureZ#90]
I'm mainly asking for compatibility, because tamed mobs from other mods will attack the dragon when hit (e.g. Mythic Mounts)

**Comment by Globox1997** [comment]
[adventurez-1.4.8.zip](https://github.com/Globox1997/AdventureZ/files/8152738/adventurez-1.4.8.zip)
Please test this

**Comment by Dejeh** [comment]
the mounts don't attack it anymore. in general though do you really "tame" it bc it doesn't give you the advancement for taming an animal

**Comment by Globox1997** [comment]
yea the player tames the dragon :)

**Comment by Dejeh** [comment]
odd because I've found that tamed wolves will _try_ to attack it in the latest version 1.4.9 (though they can't hit it?).
