### ISSUE TITLE
AdventureZ references internal Iris interfaces

### ISSUE THREAD

**Issue by coderbot16** [Globox1997/AdventureZ#93]
Please use the Iris API (net.irisshaders.api) instead.

**Comment by Globox1997** [comment]
I tried to use it with IrisApi.getInstance().isShaderPackInUse() but it always return just true, thats why I used the internal stuff instead. Does it have any draw backs?
[https://github.com/Globox1997/AdventureZ/blob/1.18/src/main/java/net/adventurez/entity/render/feature/layer/ExtraRenderLayer.java](https://github.com/Globox1997/AdventureZ/blob/1.18/src/main/java/net/adventurez/entity/render/feature/layer/ExtraRenderLayer.java)

**Comment by coderbot16** [comment]
I believe that the method was broken in 1.2.0, but it should be fixed as of 1.2.1. You can mark your mod as incompatible with 1.2.0 and below to ensure you get the correct behavior.

Other than that, the working versions of Iris should behave the exact same as the internal methods, with the difference that the API is guaranteed to stay stable from version to version, while we often refactor around the internal classes from time to time.

**Comment by Globox1997** [comment]
Alright, used api instead :)
[https://github.com/Globox1997/AdventureZ/commit/310de51de75277ba6d4fb245758bfb3c000108d6](https://github.com/Globox1997/AdventureZ/commit/310de51de75277ba6d4fb245758bfb3c000108d6)
