### ISSUE TITLE
Piglin Beast will not naturally spawn.

### ISSUE THREAD

**Issue by jabthetab** [Globox1997/AdventureZ#94]
No matter how many piglins I kill or how much nether gold ore I harvest, the piglin beast is yet to spawn naturally. Here's the log file for the modlist and possible causes.
[latest.log](https://github.com/Globox1997/AdventureZ/files/8282241/latest.log)

**Comment by Globox1997** [comment]
Should be fixed with [https://github.com/Globox1997/AdventureZ/commit/175f8a5a4b12818185b704c2d6c4b7736e931611](https://github.com/Globox1997/AdventureZ/commit/175f8a5a4b12818185b704c2d6c4b7736e931611)
