### ISSUE TITLE
Amethyst Golem Not Spawning In Geodes

### ISSUE THREAD

**Issue by junkbot173** [Globox1997/AdventureZ#95]
Tried to adjust the spawn rate values on multiple new worlds but the mob is not spawning whatsoever.

**Comment by Globox1997** [comment]
Does it happen when only adventurez is installed?

**Comment by junkbot173** [comment]
I do not know. I am thinking it was an issue with a specific modpack

**Comment by Globox1997** [comment]
Mh I mean it shouldn't happen but if a mod changes some things at the geode it might be incompatible
