### ISSUE TITLE
Please add #c:leather tag

### ISSUE THREAD

**Issue by TheButterbrotMan** [Globox1997/AdventureZ#96]
Please add an #c:leather tag to all of your leathers.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/AdventureZ/commit/2628afbf8ffdabe10788f16e03a1740b55d531df](https://github.com/Globox1997/AdventureZ/commit/2628afbf8ffdabe10788f16e03a1740b55d531df)
