### ISSUE TITLE
[BUG] Source Stone secondary ability not working 

### ISSUE THREAD

**Issue by Sebas-Re** [Globox1997/AdventureZ#97]
I tried using the Shift+ right click function to phase through blocks, but nothing happens. I see particles and hear the sound, but I'm not getting tp'd to the other side.

The wall was only 1 block wide

Using version 1.4.9

**Comment by Globox1997** [comment]
Can't reproduce it, any more information when exactly the source stone doesn't work?

**Comment by Globox1997** [comment]
Reopen if still not working with latest version
