### ISSUE TITLE
[Error]: Unknown Item adventurez:gilded_blackstone

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/AdventureZ#98]
[latest.log](https://gist.github.com/SpigotDE/ce7609f557c1bd9a8afbc01d108223b9)

**Comment by xR4YM0ND** [comment]
maybe has something to do with https://www.curseforge.com/minecraft/mc-mods/just-enough-hammers

**Comment by Globox1997** [comment]
Looks like the hammer mod is looking for a wrong string, it should be "gilded_stone" or actually "gilded_netherite_fragment" for the correct item. Not on my side if I see correctly
